### ISSUE TITLE
PIN lock

### ISSUE THREAD

**Issue by 1015PM** [stom79/mastalab#100]
I use two accounts on the app and would love some security. If you know the protonmail or whatsapp app, it has that feature.

---

Instance: None 

Mastalab version: 1.6.4.1

Android version: 7.0

**Comment by stom79** [comment]
I guess I could bring this feature with this library: https://github.com/omadahealth/LolliPin

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Please make sure the app doesn't open automatically upon entering the correct PIN. User should have to tap on the check icon after entering the PIN. This should annoy those who'll try to open the app by fluke.

**Comment by stom79** [comment]
@iknownothingaboutcomputers I think I will not implement this feature. There are many app locker that can do that work.

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Agreed.
