### ISSUE TITLE
animated gif avatar incorrect thumbnailing

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#112]
Check out @markymayhem@mastodon.art - display of avatar is incorrect in the profile and the thumbnails next to toots compared to what is on the actual site profile. 

On version 1.6.5.1.

**Comment by stom79** [comment]
My guess, it's due to the initial blank space at the bottom (needed for the animation). I will see what I can do but it's really a specific case :)

**Comment by deutrino** [comment]
This isn't an animated gif but there is a user with an image with transparency, maybe it relates? Anyway the transparency is rendered as a white background in the user profile view, but it looks correct everywhere else. @muninn@social.coop

**Comment by stom79** [comment]
@deutrino Yes, I put a white rounded background for profile picture, this choice is bad (the background color). I will fix that.

**Comment by deutrino** [comment]
Found another animated gif avatar bug - glitches appear in Mastalab but not in the user's profile in the embedded browser for @rotatingskull@mastodon.social

**Comment by stom79** [comment]
I get the same issue with the app and web UI because this avatar [is not centered](https://files.mastodon.social/accounts/avatars/000/162/793/original/3b6a9b6c270dcf6f.gif). I can do nothing with this profile picture.

**Comment by deutrino** [comment]
Weird - I was seeing tearing and artifacts on that image before, and now it's working properly.
