### ISSUE TITLE
feature: queueing future toots

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#114]
As a user who enjoys curation and posting content like art, music, etc, I would like to be able to put toots in an ordered queue to be sent at regular intervals. I would like to be able to change the order of toots in the queue, and to be able to delete a queued toot and have subsequent toots in the queue automatically shift their time to compensate for the deletion. 

This is not scheduling. To wit:

Scheduling: "send this toot at time X" 
Queueing: "every day, post a toot from the queue on P occasions between start time X and end time Y"

So, I could say, every day, post a toot from the queue on 4 occasions between 3pm and 9pm, thus a toot would be sent at 3pm, 5pm, 7pm, and 9pm.

Let me clarify with some examples based on setting to post 4 queued toots between 3pm and 9pm as I've just described. 

* If I queue 18 toots on Monday morning, then 4 toots are posted on Monday, Tuesday, Wednesday, Thursday, and 2 on Friday, at which point the queue is empty. 
* If I queue 4 toots in the morning and then delete the third toot in the queue, the queued toots are posted at 3pm, 5pm, and 7pm, *not* at 3pm, 5pm, and 9pm. This is an important point. When toots are deleted from the middle of the queue, toots further down will shift to take the place of the deleted toot. 

Additional desired functionality:

* to be able to "post now" from the queue (which deletes a toot from the queue and posts it immediately)
* to be able to move a toot from queue to drafts
* to be able to move a toot from drafts to queue

**Comment by deutrino** [comment]
Also, being able to queue boosts (see also #9) is a major part of this for me.

This entire feature request essentially duplicates the queue function on tumblr, which is absolutely indispensable to me as a curator. I would like to have fun curating on mastodon as well.

**Comment by stom79** [comment]
The main difference I see with "Queueing" and the existing "Scheduling" is that "Queueing" needs a wizard, but it will use each functionality of "Scheduling". What you describe can be done with "Scheduling" but you need to setup yourself. With a wizard, it would be done automatically. 
I will see what I can do.

**Comment by deutrino** [comment]
I really appreciate your hard work on this app, features and bugs alike. It's really great for my use case (one alt per major interest area). :)
