### ISSUE TITLE
Share > copy to clipboard does not copy anything useful to clipboard 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#117]
Steps to reproduce:

1. Tap the ... menu from a toot in home timeline 
2. Tap "copy to clipboard" 
3. Paste the result 

What actually happens:

tag:toot.cat,2017-12-10:objectId=3750177:objectType=Status

What I expect to happen:

Something resembling the url of the toot, with or without content 

---

Instance: mstdn.io 

Mastalab version: 1.6.5.1 

Android version: 7.1.2

**Comment by stom79** [comment]
I tried to reproduce this bug with several Android OS and I didn't manage to get this result.
You mean the "Copy" feature from the popup menu at the bottom right of each toot?

What I did :
- Open the popup menu at the bottom right of a toot
- Click on "Copy"
- Open the activity to write a toot
- Click past

I tried with several kind of toots (from account of the same and other instances - with and without media)...

When clicking on "copy", it simply puts the String content of the toot into the clipboard.

**Comment by deutrino** [comment]
This is intermittent for me too. I always try to reproduce a bug at *least* once before reporting but it is not 100/ reproducible for me.

**Comment by stom79** [comment]
It sounds to be the same issue mentioned in this comment: https://github.com/stom79/mastalab/issues/156#issuecomment-352729496

That does not happen every times. I will keep this issue opened and if you match it again, please give a link to the toot. I will try to understand what happens.

**Comment by deutrino** [comment]
This happened again with a toot from a GNU social instance. (Note that the original toot in this issue was from a Mastodon instance.) I also could not boost this toot from a different account than the one where I saw it (got the "oops! An error occurred!").

Text copied in Mastalab (on mstdn.io):

```tag:social.undernet.uy,2017-12-28:noticeId=1436395:objectType=note```

I can't get the direct url to the toot in question but it's the latter of two toots on https://social.undernet.uy/democracynow about Jamie Lowe dated on 11:20 am - 28 December 2017

**Comment by stom79** [comment]
Really a nice catch! I solved all issues related to GNU instances (remote actions and sharing).
You can test [the fix](https://github.com/stom79/mastalab/blob/2000d179f837084392be8808c466454dd27655c1/app/fdroid/release/app-fdroid-release-1.6.9.1-fix-share.apk?raw=true).
