### ISSUE TITLE
feature: media preview for YouTube

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#127]
It would be lovely to see a thumbnail and title for any YouTube.com and youtu.be links ☺️

**Comment by stom79** [comment]
This is not an easy matter... Preview URLs for media are returned by the API. I didn't find elements that could be gathered with youtube links (open graph or others).

**Comment by stom79** [comment]
It will be in the next release. I embed this feature with cards.

<img src="https://user-images.githubusercontent.com/30171182/34351284-f3a0ae32-ea1b-11e7-9882-8ad9af99e138.png" width="300"/>
