### ISSUE TITLE
emoji chooser displays duplicates 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#128]
I have 3 accounts configured on 3 instances. There are many duplicate emoji in the chooser, sometimes more than 3 each. 

https://framadrop.org/r/YG8H2xZZpk#V+qc/OEZgZ/mbo+3EGkHmH+qNZHTURMwV4XFsWmP6YM=

Running 1.6.5.1 on Android 7.1.2

**Comment by stom79** [comment]
That's bad. You can confirm you don't get this issue on the web app? I guess, I missed something with the primary key.

**Comment by stom79** [comment]
I had a look to this bug. I didn't find something wrong with the code. Could you confirm me that with the web app, you don't get this bug?

**Comment by deutrino** [comment]
I checked all 3 instances I have set up in the app and they aren't displaying duplicates on the web app. It looks like only mstdn.io has custom emoji, freeradical.zone and social.coop appear to be operating with the default set.
