### ISSUE TITLE
emoji autocomplete suggests emoji not supported on instance 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#129]
Steps to reproduce:

This is partly conjecture, but:

1. Have accounts set up on several instances 
2. Start composing a toot on an instance which does not support some emoji which one of the other instances does
3. Start typing the code for an emoji not supported on the instance where you are composing the toot

What actually happens:

The emoji autocomplete will suggest unsupported emoji. If you then place them into the toot and post it, they will display the code rather than the emoji both in mastalab and on the web. 

What I expect to happen:

Autocomplete should not suggest emoji which are unsupported on the instance where the toot will be posted. 

1.6.5.1 on Android 7.1.2

**Comment by deutrino** [comment]
See #128. Quite possibly related

**Comment by stom79** [comment]
Yes, it's related. It sounds that the app can't make the difference between instances. I will need more info about these instances.

**Comment by deutrino** [comment]
I'm on mstdn.io, freeradical.zone, and social.coop.
