### ISSUE TITLE
Notifications Don't Show Content Warnings

### ISSUE THREAD

**Issue by Fidgetcetera** [stom79/mastalab#130]
In the notifications tab, any notification on one of your own posts does not show the content warning for the post. This is more than a little bit annoying, as I sometimes content warn posts simply because they're long and would take up a lot of space, and they still take up all that space in the notification.

Edit: updated because I accidentally realized this happens with ALL notifications, which is especially a problem with replies. (My bad!)

---

Instance: Multiple

Mastalab version: 1.6.6

Android version: 7.0

**Comment by stom79** [comment]
> as I sometimes content warn posts simply because they're long and would take up a lot of space

I never thought they could be used for that. OK I will add this feature.

**Comment by stom79** [comment]
It will be in the next release too :)
