### ISSUE TITLE
Users Below Content Warnings

### ISSUE THREAD

**Issue by Fidgetcetera** [stom79/mastalab#131]
In the main mastodon web client, when a post with a content warning mentions a user, in reply or otherwise, the @ is displayed below the content warning even when hidden. This is immensely helpful, both in determining if a post is a reply (which could be its own issue?) and in noting who is interacting with who on a thread. 

For example, people will content warn for their public displays of affection, and I may feel weird about seeing a friend flirting with someone I don't know well, vs a friend flirting with another friend, and these are impossible to discern until I open the post. 

---

Instance: Multiple

Mastalab version: 1.6.6

Android version: 7.0

**Comment by stom79** [comment]
I never noticed that point. OK I tested it. This is just a matter how to display the content for toots (ie: Reply + content warning => put mentions at the bottom always visible). I will do that.

**Comment by stom79** [comment]
It will be in the next release
