### ISSUE TITLE
Add support for Lists

### ISSUE THREAD

**Issue by Aldarone** [stom79/mastalab#134]
Mastodon 2.1 will allow users to create lists to sort their followings. Gargamel just published the API documentation regarding this feature.

https://github.com/tootsuite/documentation/blob/4bb149c73f40fa58fd7265a336703dd2d83efb1c/Using-the-API/API.md#lists

Mastodon 2.1 is currently available as a release candidate and will come out very soon.

**Comment by stom79** [comment]
Thanks, it's an important feature to add. I will work on it.

**Comment by stom79** [comment]
It's available in the beta channel.
