### ISSUE TITLE
New approach to translations

### ISSUE THREAD

**Issue by coderemy** [stom79/mastalab#14]
I love the translations feature, and I have an enhancement suggestion. I'd like to be able to edit text prior to translation.

Giving the user control over what text gets sent to Google or Yandex is a big privacy improvement. I'd like to remove usernames, links, political sentences, personal information, etc. from posts ahead of time.

This would also put the user in control of the translation process. Accurate translation is an active process that can't truly be automated, and this lets me experiment with the text to improve my understanding. This is also great for learning a second language, since often a learner just need to know what specific words or phrases mean.

**Comment by stom79** [comment]
Thanks for the suggestion. It's a nice idea.

Currently, links and tags are removed from the text before any translations, they are stored locally with a reference:

**Links:**
- link1 => __u1__
- link2 => __u2__
- etc.

**Tags:**
- tag1 => __t1__
- t2 => __t2__
- etc.

Then when the text has been translated, they are put back into it.

See: [Source code concerning translation](https://github.com/stom79/mastalab/blob/master/app/src/main/java/fr/gouv/etalab/mastodon/drawers/StatusListAdapter.java#L942-L968)

**But I need to do the same for mentions (ie: @....)** (should be ok)

But for this part: 

>  political sentences, personal information, etc. from posts ahead of time.

I currently don't know how I will proceed... Let's see.

**Comment by coderemy** [comment]
Thanks, this is great to hear. I'm glad there are already some good safeguards in place.

I actually had these issues in mind as a *reader* when I wrote this, and I think solving them from an *author* perspective is something that should be addressed by Mastodon rather than Mastalab. It's a broader issue that would affect any app that offers translations, so I don't think it would be fair to ask you to solve it. I do like your solutions though, and I think they might be something I'd like to see in Mastodon.

Improving this for *readers* is much easier. I would like a second translate button which opens an editor rather than doing translations inline. The user can remove sentences or phrases manually before sending the text off to the translation API.

I can only think of 2 obstacles to this, but you might think of more:

1. Do the Yandex or Google Terms of Service allow for anything other than inline translations?
2. If users are too free with translations, it will raise your API usage too much.

I think the answer to the second one is to add friction. For example, only allow the user to press translate button 3 times after the view has been opened.

**Comment by stom79** [comment]
OK. Here we go.

1 - Write the toot
2 - Click on the translate icon
3 - Choose the targeted language
4 - Validate to replace the text if it's ok

Mentions / Tags / URLs / Words starting by "%" [are not sent to the API](https://github.com/stom79/mastalab/blob/translation_in_edittext/app/src/main/java/fr/gouv/etalab/mastodon/translation/Translate.java#L98-L169) (Google or Yandex).

<img src="https://user-images.githubusercontent.com/30171182/32239454-ddf0c2f2-be6a-11e7-864d-80cc97fa2042.png" width="200"> <img src="https://user-images.githubusercontent.com/30171182/32239460-e2dba6b0-be6a-11e7-905e-6002ddefce55.png" width="200"> <img src="https://user-images.githubusercontent.com/30171182/32239467-e76706f2-be6a-11e7-87d1-d883088be323.png" width="200">

**Comment by coderemy** [comment]
This is cool, wow. I definitely want this to stay, but I meant when reading toots made by other people. I want to take a more active role in translating toots I'm trying to read. I can spot political terms, typos, errors, and various phrases in the original text in the languages I see most often, so I'd like to be able to edit it to get a more accurate translation of toots I didn't write.

Sorry for the confusion. This is a really nice result of it though.

**Comment by stom79** [comment]
OK. Sorry, I read to fast :)
The main problem with this issue (IMHO) is that most people will not care about it and that's why it needs to be done automatically. 
Now, mentions are no longer sent to the API (like it is done for URLs & tags). So it's an automatic protection for original posters. 

What I can do concerning your suggestion, is to use the long click on the translate button to open a popup with the content of the toot which will be editable and then I will reuse the piece of code I did before.

Concerning API terms you mentioned, I took a few moment  to read and I removed the Google api. Even, if it's a free app with no commercial uses I can't use it.

So, with Yandex, I will try to avoid the consumption of words (timeout after a translation which has been done - in edit mode only). In "read" mode, translated toots are stored locally for a few moment to avoid useless calls (because they will not change).

**Comment by coderemy** [comment]
I agree that inline translations shouldn't be replaced by this, most people will prefer inline. I think removing mentions, tags, and links was the most important improvement for most people.

I think using long-click sounds fine, and I probably should have thought of it. The rest of this sounds great, too.

Did you have to remove Google Translate completely? Depending on the terms, maybe you can keep it for the inline translations and only use Yandex for the editable translations. I prefer Yandex myself, but I'm sure some people would miss Google for inline translations.

Thanks again, this addressed all my concerns.

**Comment by stom79** [comment]
Yes, I fully removed Google translate. Though it doesn't need an API key to work, I discovered they don't offer free plan:

> **Is there any free quota?**
> No, the Google Cloud Translation API is only available as a paid service. Please see Pricing for more details.

Source: [https://cloud.google.com/translate/faq](https://cloud.google.com/translate/faq)

**Comment by stom79** [comment]
I built a library that does not sensitive content to the API. See: https://github.com/stom79/mytransl
Mastalab works with this lib.
