### ISSUE TITLE
Crash when trying to reply to own toot from Account/Profile toots list

### ISSUE THREAD

**Issue by PhotonQyv** [stom79/mastalab#153]
Open account info page for your own account, click reply icon, to reply to your own toot, app crashes...

![screenshot_2017-12-17-12-49-57](https://user-images.githubusercontent.com/27952685/34079637-72d0cd80-e329-11e7-991b-5eaf509b5f44.png)

---

Instance: mastodon.xyz

Mastalab version: 1.6.7.2

Android version: 5.1

**Comment by PhotonQyv** [comment]
@stom79 Happens for any toot you try to reply to.

**Comment by stom79** [comment]
You frightened me! :)
OK. It's not in prod, it's when I introduced "moved accounts" (See: https://github.com/tootsuite/documentation/pull/488) a problem with parcel. Nice catch!

**Comment by PhotonQyv** [comment]
@stom79 No worries, apologies for the scare. Getting in some practice for next Halloween (;*
