### ISSUE TITLE
Sharing boosted toot send "null"

### ISSUE THREAD

**Issue by DanySpin97** [stom79/mastalab#156]
Steps to reproduce:
1. Tap on the three dots on a boosted toot.
2. Tap "Share".
3. Choose an application.

Tested on Mastalab v1.6.6, Android 7.1.2.

**Comment by stom79** [comment]
What apps did you use for these tests? I didn't manage to reproduce this bug. I put a small fix concerning the url but it should not play on this issue.

**Comment by DanySpin97** [comment]
I tried Telegram, Markor and Firefox. The result is the same in each app. Further tests shows that sharing a boost from my profile works. The issue comes up when sharing a boost from local timeline.

**Comment by stom79** [comment]
Could you confirm this bug still happens with the latest release?

**Comment by DanySpin97** [comment]
Tried the latest release on Google Play (was on latest F-Droid version). It works now.
But there is a boost shared which result in:
```
tag:social.freedombone.net,2017-12-19:noticeId=454428:objectType=note
```
Sharing other boost works fine.

**Comment by stom79** [comment]
OK. I guess an issue with that boost. I will close this issue but if you have examples, you can add them here (their URLs) and I will investigate.
