### ISSUE TITLE
Anchoring to the top newest Toot on personal timeline.

### ISSUE THREAD

**Issue by mwdowns** [stom79/mastalab#158]
This issue is in regards to reading my home timeline, not the local timeline (where the anchoring seems to work as intended). When I get to the top of my home timeline (after reading all the newest Toots) and close the app, upon re-opening the app, I am brought to the top of the home timeline with all the newest Toots. So, I have to scroll back down to the "old" top in order to see all the newest Toots. Mastalab does not seem to anchor to the first Toot in the home timeline.

However, if, after reading the newest Toots, I scroll down one Toot and the close the app, then the anchor works and when I reopen the app, I am at the same place in the timeline and all the newest Toots are loaded above.

Does this make sense? If not, I can try to clarify.

---
Instance: app on phone

Mastalab version: 1.6.7.2

Android version: 6.0

**Comment by stom79** [comment]
I want to be sure about the "close the app". Do you kill (onStop) the app or just put it in background (onPause).

<img src="https://developer.android.com/guide/components/images/activity_lifecycle.png" width="400"/>

Also, how many new toots are displayed? Because if there are only three new toots it targets the last new one instead of the last read.

**Comment by mwdowns** [comment]
First question: I use the home button (little circle on my BLU R1 HD), so I guess it goes to the background (on pause). I don't specifically kill it with the square button (brings up a broom icon).

Second question: depends, I guess, on how long it's been since I've looked at the app. So, for example, just now, I closed the app (tapped the circle button) after refreshing the timeline (swipe down) and am at the most recent Toot. I re-open the app (tapped on the Mastalab icon) 5 minutes later and there are 4 new Toots and I am at the top of my home timeline at the most recent Toot (28 seconds ago) of the 4 new toots (last Toot is 3 minutes ago).

Does that help?

**Comment by stom79** [comment]
Yes it helps. I need to improve the bookmark when the app is paused and not
killed. That's why it doesn't work as expected.

Le 18 déc. 2017 8:19 PM, "Matthew Downs" <notifications@github.com> a
écrit :

**Comment by mwdowns** [comment]
It seems to work on the local timeline, though. If do the exact same thing as above, when I re-open the app, I am anchored to the Toot I was on when I closed (the timestamp says the same when I closed it...34 seconds...even though it's 5 minutes later) and all the newest Toots are above (and the counter on the people icon shows the number of new Toots...8).

**Comment by stom79** [comment]
Yes. Home timeline works differently when paused. I will simply apply  the same treatment when the app is killed. You can have a try by killing the app and see how it will work.

**Comment by mwdowns** [comment]
Tried killing it, but it seems to jump straight to the top as well.

**Comment by stom79** [comment]
Could you test this [APK](https://github.com/stom79/mastalab/blob/dcbaeb6695d5eee5cfa31d2fd7ab23333fbaaab5/app/playstore/release/app-playstore-release-1.6.7.3-test.apk?raw=true)?

**Comment by mwdowns** [comment]
Installed it, and it seems to be working. Have twice gone to the top of the new timeline, closed the app (tapping the home button, so onPause()), and returned later to newer messages the the timeline stayed anchored at the previous "top of the timeline." Seems to work.

**Comment by stom79** [comment]
OK. Thanks for your feedback.

**Comment by mwdowns** [comment]
The anchoring in the APK seems to be working just fine.

However, the "number of new Toots" count give me a 5x number of new Toots when I close (on pause()) the app and reopen it. So, for example, if there are 4 actual new Toots, the app says there are 20.

Just noticed as I was trying to catch a refresh to make sure that the app, while doing an update of the timeline (I assume it does this on its own, without the user swiping down, periodically) said that I have 4 new Toots, but there are 0 actual new Toots. Is there possibly a hard-coded, placeholder number somewhere?
