### ISSUE TITLE
Number of followers mismatch listed followers in user card

### ISSUE THREAD

**Issue by friedger** [stom79/mastalab#16]
As discussed https://mastodon.social/@photopuck/98936345701051969

**Comment by stom79** [comment]
It's not related to the app. See: [#3307](https://github.com/tootsuite/mastodon/issues/3307)
But I wonder if the difference that we can notice now for these [count numbers](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#account) in tabs and the lists ([followers](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#getting-an-accounts-followers)/[following](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#getting-who-account-is-following)) is related to this [PR](https://github.com/tootsuite/mastodon/pull/4840)?

**Comment by friedger** [comment]
The UX should be improved. Add a link to see all followers or so

**Comment by stom79** [comment]
In fact, there is already a feature (that I need to highlight). In each profile, there is an option to open it with the built-in browser and see full information.

**Comment by stom79** [comment]
Here is the fix. A small message when the account is from another instance. This message is clickable and opens the profile page with the built-in browser.

<img src="https://user-images.githubusercontent.com/30171182/32363115-ed540db2-c06d-11e7-862d-e371991bd089.png" width="200"/> <img src="https://user-images.githubusercontent.com/30171182/32363119-ef879680-c06d-11e7-94b8-808a8c8a3a7b.png" width="200"/>

**Comment by friedger** [comment]
Nice
