### ISSUE TITLE
Cannot reply with different account 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#161]
Steps to reproduce:

1. Have multiple accounts configured 
2. Long-press to reply to a toot in timeline or thread view, select different account than the one with which you are reading 
3. Compose and hit send

What actually happens:

"Oops! An error occurred!" 

What I expect to happen:

It should work. 

---

Instance: mstdn.io and social.coop 

Mastalab version: 1.6.7.3

Android version: 7.1.2

**Comment by stom79** [comment]
Did you manage to reproduce this bug each time? If not, it could be related to other issues like a network error and so on.

**Comment by deutrino** [comment]
This has happened a couple times on different accounts/instances.

**Comment by stom79** [comment]
To fix this bug, I need to reproduce it. If it doesn't happen each time, it will be more complicated. So the only way is to find when it happens.
What timelines? Is it for boosts? Etc.

**Comment by deutrino** [comment]
This is 100% reproducible for me so far (day 2 of 2 trying anyway, haha). It's happening from within my home timeline and within threads, so far. Boosts and original toots.

**Comment by stom79** [comment]
OK. I see what happens, it's a nice catch and an ugly bug. I will fix that asap.

**Comment by stom79** [comment]
Here is [the apk](https://github.com/stom79/mastalab/blob/2bd2db0708fb481a0f3d96d50f54d67c05ffece8/app/playstore/release/app-playstore-release-1.6.7.3-bugReplies.apk?raw=true) fixing this issue.

**Comment by deutrino** [comment]
Installed and working! Thanks!

**Comment by stom79** [comment]
Great. Thanks for the feedback.

**Comment by deutrino** [comment]
I experienced something similar with a toot that also didn't copy right (see #117).

Toot in question is from a GNU social server.

I can't get the direct url to the toot in question but it's the latter of two toots on https://social.undernet.uy/democracynow about Jamie Lowe dated on 11:20 am - 28 December 2017

**Comment by stom79** [comment]
It's fixed. See: https://github.com/stom79/mastalab/issues/117#issuecomment-354324918
