### ISSUE TITLE
Cursor's Default Position is Wrong.

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#162]
After tapping the reply icon, the cursor always shows up under the username! It should ideally show up after the username (after a space, of course).

**Comment by stom79** [comment]
It's to force the capitalization of the first letter. This is not a bug :)

**Comment by pwoolcoc** [comment]
Came here for the same reason. Could this at least be configurable? I don't care about capitalizing the first letter, and I'd rather have it all on the same line.

As it is, right now when I type a reply I always start with "backspace->space" and it'd be nice to not have to do that.

If it would help, I wouldn't mind writing a PR to add a setting for this.

**Comment by stom79** [comment]
OK. Thanks, I reopen the issue.

It's here:
https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/activities/TootActivity.java#L1846

Option enabled:
`toot_content.setText(String.format("%s", (toot_content.getText().toString() + "\n\n"))); `

Option disabled:
`toot_content.setText(String.format("%s", (toot_content.getText().toString() + " \n"))); `

**Comment by stom79** [comment]
I quickly did it. It's ok.

**Comment by pwoolcoc** [comment]
I just realized I never responded after you fixed this -- so, thank you! I saw it was closed and went and updated my app and started using the new setting right away
