### ISSUE TITLE
Unable to Edit Bio

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#163]
I'm unable to edit my bio via Mastalab. I always receive an "Oops! An error occurred" after pressing 'save changes'.

Using version 1.6.6.

**Comment by stom79** [comment]
It has been fixed in release 1.6.7

**Comment by iknownothingaboutcomputers** [comment]
My bad.

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Does it take more time for a new update to show up on F-Droid? It still has v1.6.6 of Mastalab as the latest version. :/

**Comment by stom79** [comment]
@iknownothingaboutcomputers I noticed that the metadata file has been updated to the [release 1.6.7.3](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/fr.gouv.etalab.mastodon.txt). I think this release should be available soon. But yes, it takes more time to update releases with F-Droid. Also, I might publish too much...
