### ISSUE TITLE
image preview fit to width instead of crop

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#170]
I wish that images would not all be cropped to the same aspect ratio. This frequently cuts off big portions of the content, and many images (especially memes, image macros, etc) I would prefer to look at in the timeline instead of having to tap for each one. Plus, I believe that fitting thumbnails to width instead of cropping would be more aesthetically pleasing.

I have strong enough opinions on UX that I think this should be the default, but maybe some people wouldn't like it and it could be a configurable option?

**Comment by stom79** [comment]
I have no choice, media have the same limited height. Mastodon web ui also works like that.

**Comment by deutrino** [comment]
Just to clarify real quick, is the Mastodon API serving the images cropped?

**Comment by stom79** [comment]
No, at all. A media is served with its preview url (this one which is displayed in toots). In fact, as I fixed the same height to each preview picture (to keep a homogeneity between previews), I have no choice than crop these previews.

**Comment by deutrino** [comment]
Okay. The reason I submitted this feature request is because I strongly prefer seeing the whole image, more than having homogeneous previews. Small comics, memes, etc, I can read right in the timeline rather than having to tap, etc. And, I feel it looks nicer. I would be happy if this could be an option some time in the future :)

**Comment by stom79** [comment]
OK. I need to find how to display the preview URL not cropped. One good reason for this enhancement is that it will not need to load the media if the user is finally not interested after seeing the whole preview.

**Comment by deutrino** [comment]
Very tall images would still need to have their aspect ratio limited. Case in point: https://mastodon.art/users/koloquials/statuses/99154171852411751

I'd suggest 9:16 as the max "tallness" since it's very likely that mobile phones wouldn't have much of a narrower ratio than that.

**Comment by stom79** [comment]
I need to find how to display full image in the timeline (ie a simple touch on the picture?) but I can't limit them because the idea is to display the original ratio whatever its value.

**Comment by stom79** [comment]
I think #190 fixes that issue because when clicking a media you can quickly switch to all non cropped previews. That was what I planned to do. Is it ok?

**Comment by deutrino** [comment]
My personal preference would be to have to click as little as possible. I think it makes for a more immersive experience. Here is a framegrab of how it looks in the Tumblr app, including scrolling, and instances of clicking for full screen view.

Despite the Tumblr app's other issues, the actual experience of looking at media while scrolling is very smooth. Of course Mastodon has a higher percentage of text posts than Tumblr, but I would really love it if the media on Mastodon were as *easy* to experience as it is on the Tumblr app. I think if Mastalab worked like this, it would draw people to the app, and maybe to Mastodon itself :)

https://framadrop.org/r/eD4ThHLhxg#zB5DLoqqI+e7gSFQ5YiWAoCyV+LcL/40YGhbMqqP0zA=

(I am also looking to get the arbitrary cropping changed in Mastodon itself for the same reasons - it's been fixed in the glitchsoc form but not mainline.)

**Comment by stom79** [comment]
It would be easy to do that if all media kept the same standard format like in the video. For instance, how to act with this toot: https://mastodon.social/@rbonifaz/99303685513262365
(Disclaimer: only used for media examples - no idea of the content)

**Comment by deutrino** [comment]
That's a very good point when it comes to multiple images. Tumblr actually does some arbitrary cropping when there are multiple tiled images, but it lets the user reorder images and select a layout in that case, such that the user can at least make it look as nice as possible with the auto-cropping. Clearly this is impossible the way Mastodon works at present. 

I suggest that for now, we make auto-cropping look nice for posts with single images by scaling them to the full width of the timeline and not cropping until the image aspect ratio exceeds 16:10 ("landscape" shaped image) or 10:16 ("portrait" shaped image). I pick 16:10 because I think it's a good lowest common denominator between common phones and tablets when used in vertical ("portrait") orientation. How to handle this when in horizontal orientation is a good question. 

I think it's also possible to make posts with multiple images look nicer, but it quickly gets problematic when images are different aspect ratios, because if you want a nice tiled grid of previews you have to crop them based on each other's size. If you are interested, I can try to write an algorithm in pseudocode over the coming weeks - now that Mastalab is out I am sorry I haven't learned Android development but maybe this will be a reason :)

**Comment by deutrino** [comment]
I think Android 7+ has a native feature that might be usable for this. My news reader app, inoreader, pops up a "share drawer" which I have seen in other new apps, and then after a slight delay, a second drawer pops further up with the destinations (mostly chat contacts) I share to most! Maybe there is a way to populate Mastodon accounts into this? @stom79 I will DM you a video, it has names of my contacts in it so I won't post it here. But maybe it will give you some ideas.

**Comment by deutrino** [comment]
Dropping this 2.3.x preview post here because it mentions "focal points," which are relevant to the actual desire I had in posting this issue: to make image preview in Mastalab as beautiful as possible!

https://medium.com/tootsuite/progress-report-on-mastodon-v2-3-919822da47ac

**Comment by yaomtc** [comment]
Not sure if this is a separate issue, but images of a certain length are difficult to fully view within Mastalab. Here is the full view, but the bottom is cut off, and to see the bottom, I have to slide upward and hold the image in place, otherwise it either is dismissed or it snaps back down to being obscured. 
![screenshot_20180408-125006](https://user-images.githubusercontent.com/5534045/38470121-79a64d5a-3b2c-11e8-8251-8a3b7f7e2cf3.png)

**Comment by stom79** [comment]
Yes. I noticed that bug. It's a separated issue and I need to fix it. The bottom is hidden by buttons :)

**Comment by ldidry** [comment]
:+1: to this issue. I added [a little bit of css](https://framapiaf.org/@framasky/99915041412400755) to Mastodon with the Stylus extension to full-display images. Wish I could have that in Mastalab too.

**Comment by stom79** [comment]
Ah OK. It was a choice to fix the height to 200pt. You solved it with auto size for height. I can of course remove this limit for previews: https://github.com/stom79/mastalab/blob/develop/app/src/main/res/layout/drawer_status.xml#L279
I will take a look to the rendering of the previews in your instance, and I will add the feature asap.

**Comment by ldidry** [comment]
It's not on my instance: Stylus is a Firefox extension which allows to add CSS rules to the sites you visit.

**Comment by stom79** [comment]
OK. So, currently we have:
<img src="https://user-images.githubusercontent.com/30171182/39395543-10c24cda-4ae0-11e8-9bca-0e40af83efc9.png" width=400/>

I added this feature:
<img src="https://user-images.githubusercontent.com/30171182/39395546-13ee14a2-4ae0-11e8-98b4-62cf11872191.png" width=400/>

Which gives:
<img src="https://user-images.githubusercontent.com/30171182/39395547-18359f44-4ae0-11e8-8899-667da27ed871.png" width=400/>

All images can be viewed with a horizontal scroll.

**Comment by ldidry** [comment]
Could it be possible to add something to show that we can scroll ? Either a scroll bar or a tiny "scroll to see the other images" below the image?

I fear that without that indication, people won't see the feature.

**Comment by stom79** [comment]
When the toot is visible a small horizontal bar is displayed during few seconds, also as soon as it is tapped, it is displayed again.

<img src="https://user-images.githubusercontent.com/30171182/39395678-85b21024-4ae1-11e8-94e6-7146cc27c85b.png" width=400/>

**Comment by ldidry** [comment]
:+1:
