### ISSUE TITLE
Search box should be focused by default

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#171]
When I tap "search" from the sidebar it pulls up the search UI, but then I have to tap again to enter text in the test box. The text box should be focused by default - it removes an unnecessary tap and makes using the app easier with no negative impact that I can see.

**Comment by stom79** [comment]
Every text boxes are focused by default.

> When I tap "search" from the sidebar it pulls up the search UI, but then I have to tap again to enter text in the test box. 

That normal, first tap is to display search keywords.

> The text box should be focused by default

It is when you click on the "+" button.

**Comment by deutrino** [comment]
> That normal, first tap is to display search keywords.

It was not clear to me that the "search" UI is for storing saved searches, rather than for simply searching. I had no idea until just now.

> It is when you click on the "+" button.

That's what I'm complaining about. :) It appears that a major purpose of the search UI is for storing saved searches. This is something I suspect most users do a lot less often than a one-time search. I would argue that you could still put the cursor in the text box to make the common use case a bit faster, with the only downside being that the on-screen keyboard would pop up and take some of the screen area away.

Either way, thanks :)

**Comment by stom79** [comment]
>  you could still put the cursor in the text box to make the common use case a bit faster

I think we don't see this feature with the same view. For me, it's like a timeline (like you can do with the web ui and tags).  There is no need to focus on a fresh search with the keyboard opened as soon as you enter this menu. The important part is the list of tags (timelines). I am maybe not really clear :)

**Comment by deutrino** [comment]
I wonder if naming it "Saved Searches" or something might make it more obvious?? I had no idea you could use it that way :)

**Comment by stom79** [comment]
Yes, it's currently confusing. I need to rename this entry.
