### ISSUE TITLE
Log in button not working on Note 8

### ISSUE THREAD

**Issue by Luticus** [stom79/mastalab#173]
Log in button does not seem to function.  I type in the instance, the email and the password and tap log in and nothing happens.  Like not even a pop up or an error or anything.  It is as if the button is disabled or like it's just a static part of the background.  There's not animation when clicked, no login failed, no response at all.

Using a Samsung Note 8 unlocked phone, non rooted, stock image.

---

Instance: mastadon.social

Mastalab version:  1.6.7.3

Android version:7.1.1

**Comment by stom79** [comment]
When typing the instance "mastodon.social", does it suggest a list of instances? When the client id is retrieved, the login button is enabled. So the problem comes from this point.

**Comment by Luticus** [comment]
It does actually suggest exactly one instance:  mastadon.tescher.me

**Comment by stom79** [comment]
you can confirm that you typed exactly "mastodon.social" in the first field? Then when going to the next field (ie: focus is lost for the instance field), it should enable the login button.

**Comment by stom79** [comment]
There is a mistake in the name: mast**A**don.social it's mast**O**don.social. That's why only mast**A**don.tescher.me is suggested.

**Comment by Luticus** [comment]
HAH.  Color me dumb  :)  Spelling for the win huh..... 

Thanks for the help  :)

**Comment by stom79** [comment]
you're welcome :)
