### ISSUE TITLE
Hide Post Numbers

### ISSUE THREAD

**Issue by Fidgetcetera** [stom79/mastalab#175]
I've seen a few people post that they're not big fans of seeing the number of boosts and faves on posts. I'm also on a small three-user instance (with all 3 users being myself) where those numbers are rarely accurate or helpful. It'd be quite nice to just be able to choose not to show the numbers next to the boost and fave buttons at all. 

---

Instance:

Mastalab version:

Android version:

**Comment by stom79** [comment]
I added an option in settings (checkbox) which allows to hide them. It will be in the next release.
