### ISSUE TITLE
"fetch more toots" causes scroll position to jump 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#180]
When I reach the "fetch more toots" button and tap it, sometimes my scroll point will be reset to the top, and on one occasion, the toots were loaded above my scroll point. 

---

Instance: multiple 

Mastalab version: 1.6.8 from the ticket about replying from different account 

Android version:

**Comment by stom79** [comment]
It should not happen since #158. Could you please try the [last release](https://github.com/stom79/mastalab/releases/tag/1.6.8)
I didn't notice, I kept this release to the draft status... I just published it

**Comment by deutrino** [comment]
I've installed and will report back.

**Comment by deutrino** [comment]
As of 1.6.9 they are usually loading *above* the "fetch more toots" button, meaning I have to scroll up through all of them once they load. They should load below.

**Comment by stom79** [comment]
This is due how it works. See: https://github.com/stom79/mastalab/issues/34#issuecomment-343993447
I have no choice due to pagination issue (I guess it is). See: https://github.com/stom79/mastalab/issues/34#issuecomment-343758741
