### ISSUE TITLE
App fails to save the changed visibility of a toot when saved as a draft.

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#186]
**What Happened**:

I composed a toot, changed its visibility from default (followers only) to 'mentioned user only', and then saved it as a draft. Upon reopening the draft, I noticed that the visibilty of that toot had been automatically changed to 'Public'. This happened every time I saved a toot as a draft.

**What Should Happen**:

Mastalab should save the visibilty of a toot saved as a draft **that's been chosen by the user** and not switch it to Public (which isn't even the default choice in my case).

-----

Mastalab version: v 1.6.6

Android version: 5.1

**Comment by stom79** [comment]
I forgot to take this parameter in "autosave" (ie: changing "only" the visibility didn't trigger autosave). 
But for replies, there is clearly the bug you mentioned.

**Comment by stom79** [comment]
The visibility was overridden for replies. It's fixed.
