### ISSUE TITLE
Hide Replies from Showing Up in Profile TL

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#187]
When I open my profile in the app, I see my own replies cluttering the TL. Would be nice if we could hide the replies from showing up on the profile TL.

---
Mastalab version: 1.6.6

Android version: 5.1

**Comment by stom79** [comment]
Please, have a look here: https://github.com/stom79/mastalab/wiki/Filter-toots

**Comment by stom79** [comment]
My bad (I closed this issue too fast), you want the same feature for the profile page.

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Could you please add the link to this wiki in the app's 'About' page? I see you've given the link to your GitHub page in there but it's listed beside 'Source Code'. Not sure how many users will actually open that particular link (for obvious reasons). But a direct link to the Wiki page will be very useful, I'm sure.

**Comment by stom79** [comment]
@iknownothingaboutcomputers sure! It's done.

**Comment by stom79** [comment]
I added the two new filters (boosts/replies). See attached pictures.

<img src="https://user-images.githubusercontent.com/30171182/34318345-b36c8c80-e7c5-11e7-830e-0ca28430f4bc.png" width=200/> <img src="https://user-images.githubusercontent.com/30171182/34318347-b46720be-e7c5-11e7-9c87-3dd876ea25ee.png" width=200/>

**Comment by LeeteqXV** [comment]
Excellent! :-)

@LeeteqXV

**Comment by v01d** [comment]
Hey, just found about this feature. However, I would like this to be set for all users by default. Is it possible to do that?
