### ISSUE TITLE
Position of the floating action button isn't based on Material Design Guidelines

### ISSUE THREAD

**Issue by Rintan** [stom79/mastalab#205]

**Comment by stom79** [comment]
Thank you. Just a side note for me.

> The floating action button should be placed 16dp minimum from the edge on mobile and 24dp minimum on tablet/desktop. [Ref](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button).

The 16dp is not respected. See: https://github.com/stom79/mastalab/blob/develop/app/src/main/res/values/dimens.xml#L8

**Comment by stom79** [comment]
OK. It's fixed. Thanks for paying attention to this point.
