### ISSUE TITLE
mastalab does not honor HTTP Strict Transport Security

### ISSUE THREAD

**Issue by js0000** [stom79/mastalab#209]
the federated mastondon instance i use, toot cat, had it's cert expire. firefox refused to connect, since it is a HSTS configured webserver. i got the notice below when trying to connect:

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

and this:
toot.cat uses an invalid security certificate.
The certificate expired on 12/30/2017 09:46 AM.
The current time is 12/31/2017 12:32 PM. 

of course, i must mention that the fact that mastalab would ignore HSTS allowed me to connect and do some business that i otherwise would have not. but i thought perhaps the developers should know about it.

btw, let me also thank you for mastalab- i use it every day and recommend it whole heartedly to any other tooters i can!

---
Instance: toot.cat
Mastalab version: 1.8.7.3
Android version: 7.1.2 (LineageOS)

**Comment by stom79** [comment]
The fix will be in the next release.

**Comment by js0000** [comment]
thank you! now i love mastondon even more! 💗
