### ISSUE TITLE
timed muting

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#210]
Feature request: ability to mute a user for 1, 3, 8, 24, 48 hours.

Bonus request: ability to do the same with a thread.

The only thing this should do is hide new toots in the timeline for the duration (possibly even as expandable "collapsed" toots), they should be visible when directly opening the user's profile (or the thread) etc.

**Comment by stom79** [comment]
> The only thing this should do is hide new toots in the timeline for the duration

I am not sure to understand the purpose? You can mute a user and keep notifications from this user (I added this feature recently).
Also, you can use lists to create custom timelines and discard some users.
I will close this ticket, but I guess it could be added as a feature in the project concerning the wizard to queue some tasks.

**Comment by deutrino** [comment]
Sure, I'm happy to explain my reason for suggesting the feature. Sometimes a particular user is posting a lot and I don't want to see their posts for a while, but would forget to unmute them if my only option is to mute indefinitely. A timed mute feature solves this problem.

For what it's worth, I'll probably ask for this in Mastodon itself at some point.

**Comment by stom79** [comment]
OK. I understand the idea. For sure, this should be done by the instance because it's easy to manage it in db: mute + date -> toots are not displayed if current_date < mute_date.
From the app, it's harder and unstable. If the app fails to unmute the user, you will miss his/her toots.
But I can introduce a "fake" mute with the app. I record the date of muting and don't display the toots for the particular user in the  home timeline only. But it will only work with the app.
If you think it could be interesting, I can reopen the ticket and flag it as an improvement.

**Comment by deutrino** [comment]
I would be very interested in that feature. Maybe some other people will comment if they are as well. Thanks :)

**Comment by deutrino** [comment]
Just adding that discussion of this on the server side is happening in tootsuite/mastodon#1593

**Comment by stom79** [comment]
OK. I reopen the issue. If the app has several accounts, it will be applied for all of them.

**Comment by stom79** [comment]
OK. Here is a working example:

<img src="https://user-images.githubusercontent.com/30171182/34576759-4aa03be8-f17f-11e7-86f9-520472679a74.png" width=200/>
<img src="https://user-images.githubusercontent.com/30171182/34576762-4c83fbb6-f17f-11e7-8da3-b5376ae84b5a.png" width=200/>
<img src="https://user-images.githubusercontent.com/30171182/34576764-4fa3ffd0-f17f-11e7-9268-3cd00ec56d79.png" width=200/>
<img src="https://user-images.githubusercontent.com/30171182/34576765-523adce6-f17f-11e7-8078-cf0799fb827c.png" width=200/>
<img src="https://user-images.githubusercontent.com/30171182/34576771-5524b6b6-f17f-11e7-9835-5fe2da2c393d.png" width=200/>
<img src="https://user-images.githubusercontent.com/30171182/34576775-57974c7e-f17f-11e7-831d-af7c9e65cbc5.png" width=200/>
<img src="https://user-images.githubusercontent.com/30171182/34576776-5a4741a4-f17f-11e7-90bc-5ecd13aa33ca.png" width=200/>
