### ISSUE TITLE
Blocked user's boosts sometimes appear in home timeline

### ISSUE THREAD

**Issue by Fidgetcetera** [stom79/mastalab#212]
When following someone who boosts a user you have blocked, their posts will still be shown in your feed. This doesn't seem to occur with mutes, but may be worth double checking with more testing.

---

Instance: https://sins.center

Mastalab version: 1.6.9

Android version: 7.0

**Comment by stom79** [comment]
This bug should be fixed by the mastodon project itself. It's impossible to put this fix inside the app, because it would need to check the relationship (= server query) for each boost and then display it or not depending of this reply.
