### ISSUE TITLE
Images in alt-text entry stretch

### ISSUE THREAD

**Issue by Fidgetcetera** [stom79/mastalab#213]
Fairly simple issue, but the implementation on fixing it may be worth discussing. When you open an image to enter a description for it, it will stretch to the current screen size, affected by the keyboard. This heavily distorts the image you're trying to view. 

A decent solution may be to simply show the fullest size you can without stretching, and if the keyboard would hide any of it, crop it and allow for scrolling, so that you can see the full image at any point and still at a good resolution. 

---

Instance: https://sins.center

Mastalab version: 1.6.9

Android version: 7.0

**Comment by stom79** [comment]
It's done.
