### ISSUE TITLE
Editing long CWs and toots is difficult 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#221]
The UI doesn't allow to see more than one line of text in the CW input field. Also, in that and the toot text field itself, scrolling is difficult when the height of the text is greater than the height of the field. 

https://framadrop.org/r/3FZ-sBFYoY#XVvZ0snzBSUCnwNzgkUZ4cEo8Kf8LCcQnfg4AhnzJW4=

---

Instance: multiple 

Mastalab version: 1.7.0

Android version: 7.1.2

**Comment by deutrino** [comment]
Specifically regarding the lack of scrollbars, I can "scroll" within the toot or CW text by dragging the input cursor, but it's a painful experience compared to being able to scroll to the area I want and then tap to place the cursor.

**Comment by stom79** [comment]
> I can "scroll" within the toot or CW text by dragging the input cursor

You can scroll the toot with the scroll bar whatever its length without any pain (I tested with +2500 chars). I removed the limit of one line for the CW field.

<img src="https://user-images.githubusercontent.com/30171182/34532779-af725466-f0b7-11e7-881c-de9fb2d8848e.png" width="300"/>
