### ISSUE TITLE
Automatically retain the content warning in boosts and replies

### ISSUE THREAD

**Issue by coderemy** [stom79/mastalab#23]
Replies don't seem to automatically include content warnings at all.

Boosts with a content warning now have a content warning rather than *no* content warning, but it seems to be blank.

It should also maybe be editable with boosts if that's possible, since the warnings used by the original poster and the warnings I want to supply my audience might differ. This is a secondary concern until the web versions support this, though.

**Comment by stom79** [comment]
Thanks for the report.

> Replies don't seem to automatically include content warnings at all.

I tested and I got the content warning in replies. Could you give example of "public" toots concerning this issue?

> Boosts with a content warning now have a content warning rather than no content warning, but it seems to be blank.

I can't reproduce this issue, could you give me an example?

Unfortunately, boosts are not editable. I can't do anything.

**Comment by coderemy** [comment]
I had the wrong idea about how this works. When I boost a post with a content warning, I get a show more button, but I don't see the content warning itself.

![2017-11-05-1509906263](https://user-images.githubusercontent.com/33130034/32417774-519759f2-c224-11e7-8781-ff65b81856db.png)

I see the content warning on the web version, though.

If I hit reply to a post with a content warning, the CW isn't already filled in. I have to add it manually. I can see CWs in other people's replies though. I think I was unclear on this one

**Comment by stom79** [comment]
Oh. Ok. I will fill automatically the CW field for replies.
