### ISSUE TITLE
[Feature request] Swipe down/up to close the image viewer

### ISSUE THREAD

**Issue by jpdeplaix** [stom79/mastalab#231]
When you click on an image it opens the image viewer and two ways can be used to close it:
* the close button on the upper-left side of the screen
* the physical return button

I was wondering if it were possible to add an other way: swiping down or up like the [Twidere app](https://github.com/TwidereProject/Twidere-Android/) does ?

**Comment by stom79** [comment]
I added a swipe right (to keep consistency with the previous animation) that allows to close the media activity if:
- No pinch zoom & Media position = 1/x (x:1..4)

**Comment by jpdeplaix** [comment]
Thanks ! I'm curious, what is the previous animation ?

**Comment by stom79** [comment]
the furtive slide from right to left :)
