### ISSUE TITLE
Attached images don't display in notification timeline

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#233]
When I get notifications (faves) of my toots with images, they don't display in the notification timeline. 

---

Instance: freeradical.zone 

Mastalab version: 1.7.2

Android version: 7.1.2

**Comment by stom79** [comment]
Yes, it was a choice :) I reproduce what is done with the web UI.

**Comment by deutrino** [comment]
Ahh okay. It seems weird to me, and in some cases I post images with only a hashtag or two and forget what I posted. I noticed today because this happened with a toot with a CW and when I tapped "show more" I expected an image to appear!

I use Mastalab for 95% of my interaction with Mastodon so I didn't even remember this was the case with the web UI. :)
