### ISSUE TITLE
Dates are sometimes truncated

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#234]
Some post dates are truncated in the timeline. See screenshot :) 

https://framadrop.org/r/LxkmH7HDe6#kxj4YAbQlJXfZOzrTanCUNjZAHc3pAKAS5g85L679lA=

---

Instance: all

Mastalab version: 1.7.2

Android version: 7.1.2

**Comment by stom79** [comment]
They are not truncated, I failed to remove the last slash :). I will fix that.

**Comment by stom79** [comment]
Just to be sure, what is the real date? You should get it when clicking on the truncated date. Are these toots older than one year?
