### ISSUE TITLE
No automatic refreshing of the home timeline

### ISSUE THREAD

**Issue by brabalan** [stom79/mastalab#238]
My home timeline does not automatically refresh. If I know there are more recent toots, I can go all the way up and I do not see them. If I pull down I trigger a manual refresh, and I see the new toots, but I've lost my place.

The surprising thing is that the notification timeline works correctly, it is updated automatically.

---

Instance: framapiaf.org

Mastalab version: 1.7.2 from F-droid

Android version: Android 7.1.2, lineageOS (January 5 update)

**Comment by brabalan** [comment]
As a follow-up, if I enable system notifications (second tab of the settings), automatic refreshing then works.

**Comment by stom79** [comment]
Thanks it will help to fix this issue.

**Comment by stom79** [comment]
OK. It's fixed.

**Comment by brabalan** [comment]
I'm sorry but this did not fix it for me. If I disable notifications, I do not have automatic refresh.

What I currently do it to relaunch the app, as it's the only way to update my timeline without losing my place. Could it be possible to have a refresh button that does not loses one's place?

**Comment by brabalan** [comment]
I searched for `SET_LIVE_NOTIFICATIONS` and I'm wondering if the issue might not be there: https://github.com/stom79/mastalab/blob/33aaee824fc8a602bf3031ef7e10e803cfca7c61/app/src/main/java/fr/gouv/etalab/mastodon/activities/BaseMainActivity.java#L1666
