### ISSUE TITLE
after viewing full-resolution image once, it's not displayed on subsequent views

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#242]
Steps to reproduce:

1. Scroll in the timeline to find a preview image (it's best to pick one with sharp lines so the effect is easy to see) 
2. Tap the preview to display the full image 
3. Back out of the full image display 
4. Tap the preview again to display the full image 

What actually happens:

The full image is now not displayed, only the scaled-up preview. This is visible as pixelization, blurring, etc. 

What I expect to happen:

The full image is always properly displayed. 

Mastalab version 1.7.2

**Comment by stom79** [comment]
I noticed that bug yesterday and I fixed it in this commit https://github.com/stom79/mastalab/commit/652de3c51330e1f25f0ef3ecf7d1887d7762c501
