### ISSUE TITLE
Mastalab crashes when changing accounts

### ISSUE THREAD

**Issue by hellocam** [stom79/mastalab#244]
I have three accounts, one on octodon.social, ephemeral.glitch.social, and tootplanet.space. When I switch between octodon and tootplanet, I don't have any problems. But when I go from octodon or tootplanet to ephemeral, Mastalab crashes.

I saw that someone commented on Google Play about Mastalab crashing regularly on their Xiaomi phone, and yes, I have a Xiaomi, too.

---

Instance: octodon.social, ephemeral.glitch.social*, tootplanet.space

Mastalab version: 1.7.2

Android version: AICP OTA 12.1 nightly (20180108)

**Comment by stom79** [comment]
Thanks. I am pretty sure to understand what's going wrong. I recently introduced a bookmark which allows to keep the current position in TL even when the app is destroyed. ephemeral.glitch.social doesn't keep statuses for a while, so the bookmark is  lost and the app must poorly handle this case. I will fix that asap.

**Comment by hellocam** [comment]
I checked today and it didn't crash! 💯
