### ISSUE TITLE
Add camera option when shearing image FR

### ISSUE THREAD

**Issue by felixgonsug** [stom79/mastalab#253]
It would be nice to have the option to take a picture for shearing in a toot and not only browse it in the gallery.

---

Mastalab version: 1.7.4 (f-droid)

**Comment by stom79** [comment]
I never implemented it, because I find the permission CAMERA quite intrusive. It's just my opinion. I would like more opinions from others on that issue.

**Comment by felixgonsug** [comment]
Aaah, shure is quite intrusive. But its FOSS so we can be sure it wont spy and you can deny that particular permission if you don't care about taking pictures outside the app.
