### ISSUE TITLE
YouTube embed in conversation starts appearing in multiple toots

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#263]
While browsing a conversation, I noticed that a YouTube embed from one toot was appearing in several others as well, not right away, and not always the same toots upon subsequent examination. Sometimes it would suddenly appear upon interacting with a toot (faving etc) but I couldn't easily reproduce that part in this attached video:

https://framadrop.org/r/ilE7NnGwhl#eQfR9fv0gaDDF1py5j79STzpu2MKFaoI9s5AmYxZOjo=

The video begins in Firefox, where I show the thread as it is rendered on mstdn.io, and then navigate to the bottom and click the YouTube link so you can see the video. Then I switch apps to Mastalab and scroll in the conversation, at which point the video starts appearing in several places. 

Relevant conversation starts on toot
https://mstdn.io/@angristan/99381474337975414

---

Instance: mstdn.io 

Mastalab version: 1.7.5 

Android version:7.1.2

**Comment by stom79** [comment]
I can't reproduce that bug, but I am running 1.7.6 which fixes an issue with videos and cards. See: https://github.com/stom79/mastalab/releases/tag/1.7.6

**Comment by stom79** [comment]
OK. Solved. Thanks for the report.

**Comment by deutrino** [comment]
Nice one!
