### ISSUE TITLE
Jumpy Media View

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#282]
It's hard to view images in a smooth manner. The page jumps a bit when I tap to move to the next/previous image. Needs smooth transition asap.

---
Mastalab version: 1.7.6
Android version: 5.1

**Comment by stom79** [comment]
Did you try to swipe the screen?

**Comment by iknownothingaboutcomputers** [comment]
I'll answer this question later today. Sorry for the late reply.

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Swiping makes no difference. The culprit is the 'Save' option which appears when you tap or swipe the image. I think you should make that option appear only when the user taps in an area above the image.

**Comment by deutrino** [comment]
Or maybe the save icon be a floating button which appears on a tap or something. The "jumpiness" bothers me a little as well.
