### ISSUE TITLE
Add Contributing + Setup Guide

### ISSUE THREAD

**Issue by jalcine** [stom79/mastalab#29]
It's early but this project can take off! I'm hoping that you'll be open to adding a contributor guide for new developers.

I have experience with Android applications so I can help with crafting the setup guide.

https://www.contributor-covenant.org/ is a good sort.

**Comment by stom79** [comment]
Thanks, I will need your help for writing the setup guide. Currently, I only ask to PR on the develop branch.

**Comment by jalcine** [comment]
Ah! My bad (re: last PR then). I'll send something for review.

**Comment by stom79** [comment]
I never wrote it - The setup guide will help.

**Comment by jalcine** [comment]
Okay so re: `develop`, that might need some work on your end. Firstly, you'll have to [set `develop as the default branch][1].

Also is that the same on the Bitbucket repo? If so, a note about sending + checking requests there as well will be needed.

[1]: https://help.github.com/articles/setting-the-default-branch/

**Comment by stom79** [comment]
OK. I need to be sure that F-Droid targets the master `branch` by default and will not take the `develop` once I will put it by default. The current [metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/fr.gouv.etalab.mastodon.txt) is:

```
[...]
Build:1.5.7,67
    commit=1.5.7
    subdir=app
    gradle=fdroid
    prebuild=sed -i -e '/jcenter()/a\        google()' ../build.gradle && \
        sed -i -e '/safetynetImplementation/d' build.gradle

Auto Update Mode:Version %v
Update Check Mode:Tags
Current Version:1.5.7
Current Version Code:67
```

**Comment by jalcine** [comment]
Is there a way to specify what branch to check out when doing F-Droid builds? Or to pass a particular ref (like a tag)?

I'll look into this as well - I don't want to break the existing flow unnecessarily.

**Comment by stom79** [comment]
I asked the [question](https://gitlab.com/fdroid/fdroiddata/commit/4f137b933d7a0a7dd8edd71f999686a2be9fc40f#note_46588011). We will wait their reply.
