### ISSUE TITLE
Do not add a newline before (and after) usernames in replies

### ISSUE THREAD

**Issue by jpdeplaix** [stom79/mastalab#291]
When replying to somebody (or several people), the user you are replying to is going to appear before the cursor with a newline in between and the other mentioned users are going to appear at the end with a newline at the end as well (and between each usernames ?, I can't tell).
Is it possible to have the same behaviour than with the webapp ? i.e. each usernames separated by a space and the cursor at the end.

Mastalab version: 1.7.6

**Comment by stom79** [comment]
Related to #162 (closed). https://github.com/stom79/mastalab/issues/162#event-1411740550
Option disabled will be changed into:

> @account_reply @account1_in_conversation @account2_in_conversation blabla blabla blabla blabla blabla blabla
> blabla blabla blabla blabla blabla

**Comment by jpdeplaix** [comment]
Awesome, thanks ! Where is the option ? I can't find it (using 1.7.8)

**Comment by regagain** [comment]
The option is called "First letter in capital for replies"
