### ISSUE TITLE
Loading more recent toots jumps timeline to top

### ISSUE THREAD

**Issue by georgedorn** [stom79/mastalab#293]
Step to reproduce:
1. Scroll back in main timeline for at least 40 toots.  Easier to see if you go back a day.
2. Kill the app.  This simulates not launching the app for a day.
3. Load the app.  Timeline is where you left off.
4. Try to scroll up.  There are no toots, so the app requests some from the instance.
5. When toots are loaded, one of two things happen (apparently randomly?).  Either the timeline position jumps to the most recent toot immediately, or it shows the "Load More Toots" button briefly and then jumps to the most recent toot.

---

Instance:  social.coop

Mastalab version:  Initially discovered issue in 1.7.4; issue remains in 1.7.8.

Android version:  7.1.2

**Comment by stom79** [comment]
1,2 - 3:  OK.

>  There are no toots, so the app requests some from the instance.

4: Not sure to understand. The behavior should be this one: https://github.com/stom79/mastalab/issues/34#issuecomment-343993447

**Comment by georgedorn** [comment]
4:  When I kill the app and launch it again, the top toot in the timeline is the one I left off on.  I cannot scroll up, there are no more toots.  Scrolling up seems to trigger an API call to load more.  There is no Fetch More button, though sometimes in step 5 the button appears briefly before the timeline jumps to the most recent toot.

**Comment by deutrino** [comment]
This is what I reported in #180

**Comment by stom79** [comment]
OK. I didn't understand, that means the answer is here: https://github.com/stom79/mastalab/issues/180#issuecomment-354274017
