### ISSUE TITLE
Can't see all draft if too many of them

### ISSUE THREAD

**Issue by Dostoi** [stom79/mastalab#294]
If you have more than 11 drafts, you can't keep scrolling down, you're stuck at the 11th one and can't see the others. 

Instance: Framapiaf
Mastalab version: 1.7.8
Android version: 5.1.1

**Comment by stom79** [comment]
There is an overlay with the last draft (content is truncated), but I can't notice a limit. Could you please save more toots and confirm that you can't see them or that the number of drafts remain unchanged?

**Comment by Dostoi** [comment]
Hum seems like it was just the truncated content that made me think that. I'll come back when I have tooted everything
Might be a false alarm, sorry ^^
