### ISSUE TITLE
App Crashes!

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#298]
App crashes every time I try to attach a pic to a toot.

Mastalab version: 1.7.8

Android version: 5.1

**Comment by stom79** [comment]
It's fixed but not released. I guess you disabled resize for pictures (please use 2Mo or 1Mo).

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Oh, yes! I have disabled it. Thanks for fixing it, Stom (Trooper)! :D
