### ISSUE TITLE
Conflicting action with left-to-right swipe on media

### ISSUE THREAD

**Issue by jpdeplaix** [stom79/mastalab#299]
After #231 a left to right swipe feature was added to close media such as pictures.
However, left-to-right is probably not a good way to close it as it's conflicting with left-to-right swipe to go to the next picture in case there are more than one picture to see.

Could you change this feature from left-to-right to down-to-up ?

Mastalab version: 1.7.8

**Comment by stom79** [comment]
This issue will be fixed with https://github.com/stom79/mastalab/issues/282
