### ISSUE TITLE
Default post visibility settings option disappears with locked account

### ISSUE THREAD

**Issue by michael-ball** [stom79/mastalab#300]
I have a locked account on mastodon.social but have set the default post visibility to "public" via that instance's settings on the web interface. However in Mastalab, when I go to the settings for that account, the default post visibility option is missing, and all my posts/replies default to "post to followers only".

Instance: mastodon.social

Mastalab version: 1.7.8

Android version: 7.1.2

**Comment by stom79** [comment]
Side note for myself: 

- Enable the button for visibility in settings for locked accounts. See: https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/fragments/SettingsFragment.java#L437

- Change condition in TootActivity: https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/activities/TootActivity.java#L418
