### ISSUE TITLE
Fetching new toots from the bottom

### ISSUE THREAD

**Issue by alanz** [stom79/mastalab#302]
If you re-open the app after a while, it retains your position, showing toots from several hours before, and has a thing you can click labelled "Fetch more toots" to load more, which then loads up to 40 of them.

At the moment, it loads the most recent 40, then presents the same button if it has not fully caught up.

Please provide an option to load from the bottom instead, so if the last toots shown are 11 hours old, it loads 40 toots from 11 hours ago.

This allows you to load these toots, read them, then load the next batch.

---

Instance: social.coop

Mastalab version: 1.7.8

Android version: 8.0.0 (OP5)

**Comment by stom79** [comment]
It sounds to be related to #293 and #180.
Please, see the reply [here](https://github.com/stom79/mastalab/issues/180#issuecomment-354274017) for more details.
