### ISSUE TITLE
Search icon in Side Menu

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#309]
I suggest moving the search icon to the side menu permanently. Or at least giving the option to hide it for those who, like me, rarely use it. It's just cluttering the UI.

---

Mastalab version: 1.7.8

Android version: 5.1

---

**Edit**: Added the word "permanently" b/c I forgot that 'Search' is already available in the side menu.

**Comment by stom79** [comment]
It sounds to be a duplicate with your ticket #12

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Oops! Really sorry.
