### ISSUE TITLE
Mastalab not installing/deinstalling

### ISSUE THREAD

**Issue by alsternerd** [stom79/mastalab#31]
Since Mastalab 1.5.6 instllaing or deinstalling it results in a crash of the ApkInstaller, the Error I get through logcat is:

`E( 4284) Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob64.bin (ApkAssets)`

It also crashes the phone, when trying to start the UI of Mastalab, while notifications kept coming in.

Sadly this above is the only logout for this issue, since the systemcrash does not generate any.

Reinstallation tested with https://github.com/stom79/mastalab/blob/develop/app/fdroid/release/app-fdroid-release-1.5.8-new.apk?raw=true and https://github.com/stom79/mastalab/blob/develop/app/fdroid/release/app-fdroid-release-1.5.8.apk?raw=true.

Installation or deletion via F-Droid results in an instant crash of the ApkInstaller. Trying to remove it via Settings -> Apps results in a settingscrash, while trying to open the Apps-part.

Used OS and Device:
http://konstakang.com/devices/kis3/CM13/

LineageOS13 by konstakang on the ZTE Open C. (May also be a memory issue, but previous versions worked fine.)

New testing: Installation via F-Droid worked, but it still crashes the phone while trying to start it. (Still no entry in any logs.)

**Comment by stom79** [comment]
Could you try to uninstall for all users? And then restart a fresh install.

![device-2017-11-08-145254](https://user-images.githubusercontent.com/30171182/32552566-a9cba228-c494-11e7-8026-e89cc56bbf86.png)

**Comment by alsternerd** [comment]
> Could you try to uninstall for all users? And then restart a fresh install.
The problem is that I can't even get to this point, due to the crashing Apps section in the settings. I could go and try to remove it via adb. I will try to reset my phone on the weekend, so that I can work with a clean install on this.

**Comment by stom79** [comment]
Could you access the app through `Settings > Storage > Apps >` instead of `Settings > Apps >`?

**Comment by alsternerd** [comment]
> Could you access the app through Settings > Storage > Apps > instead of Settings > Apps >?

Didn't work either, the Apps menuepart (or maybe app itself?) crashes through this way too. Cleaning the Caches didn't work.

**Comment by stom79** [comment]
It will be hard to understand why the app makes this bug with settings...

**Comment by alsternerd** [comment]
> It will be hard to understand why the app makes this bug with settings...

That's the bad news. :(

I now wiped the whole cache, it may have helped it. I hope it's on my site.

**Comment by stom79** [comment]
OK. I will compile it with Android SDK Platform 27 (revision: 1). Would you agree for a last test?

**Comment by alsternerd** [comment]
> OK. I will compile it with Android SDK Platform 27 (revision: 1). Would you agree for a last test?

I do and hope this works.

**Comment by stom79** [comment]
OK. Here is the [new apk ](https://github.com/stom79/mastalab/blob/develop/app/fdroid/release/app-fdroid-release-1.5.8-BT27.apk?raw=true) with build tools 27

**Comment by stom79** [comment]
Great!!! Thanks a lot for your contribution.
