### ISSUE TITLE
Black Theme

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#310]
With my old phone and its old battery, every little bit that helps in saving juice is more than welcome. Besides, who doesn't like black theme?

_"The theme is black and full of wonders."_ -- Melisandre, Game of Thrones.

---

Mastalab version: 1.7.8

Android version: 5.1

**Comment by jpdeplaix** [comment]
Isn't it the theme by default ? What's wrong with the Night mode ? (Settings -> Night mode)

**Comment by stom79** [comment]
Adding a new theme is not an easy matter. If someone makes it, why not. Also, I agree with @jpdeplaix, there is already a dark theme (default theme).

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Ok. Close this issue, then.

**Comment by iknownothingaboutcomputers** [comment]
@stom79 Ok. Close this issue, then.

**Comment by iknownothingaboutcomputers** [comment]
@jpdeplaix Night mode is blue. Black theme will be black. Black is better, I feel. But it's ok if dev is fine with night mode.

**Comment by jpdeplaix** [comment]
blue ? I mean dark/grey ok, but do you really see that blue ?

**Comment by iknownothingaboutcomputers** [comment]
@jpdeplaix Dark blueish, yeah.
