### ISSUE TITLE
text cut off

### ISSUE THREAD

**Issue by schiessle** [stom79/mastalab#317]
Since the update to version 1.7.9 (F-Droid) the text is cut off for some toot's.

This is how it looks in the time line:

![_20180212_232028](https://user-images.githubusercontent.com/1589737/36138902-ae8286bc-109b-11e8-837a-edbf8b7d192d.JPG)

And this is how it looks if I open the toot:

![_20180212_232106](https://user-images.githubusercontent.com/1589737/36138913-bb06f99a-109b-11e8-86d3-69abbca8f7ef.JPG)

From what I can tell it only happens to toot's with links and only for toot's from GNU Social or Friendica users. Toot's from Mastodon users look fine. In the web interface of Mastodon everything looks fine, therefor I don't think that it is a general incompatibility between the networks.

**Comment by stom79** [comment]
Yes, sorry for that bug. It's fixed in [1.7.9.1](https://github.com/stom79/mastalab/releases/tag/1.7.9.1) and it should be available soon on [Fdroid](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/fr.gouv.etalab.mastodon.txt#L247).

**Comment by iknownothingaboutcomputers** [comment]
@stom79 The big empty space between last line of the text and the icons below it has returned in 1.7.9.1. You had fixed it in the previous version.

**Comment by stom79** [comment]
@iknownothingaboutcomputers I reopened the ticket #308
