### ISSUE TITLE
Some links do not display correctly

### ISSUE THREAD

**Issue by Risen-phoenix** [stom79/mastalab#318]
Sometimes, links are cut off and not displayed fully. I've attached a few screenshots, but it seems like this regularly occurs when viewing toots from @debian@quitter.se
Examples: 
[
![screenshot_2018-02-13-06-58-54](https://user-images.githubusercontent.com/15039983/36148856-6c8e2528-108b-11e8-83e7-22f66a35c492.png)
](url)
![screenshot_2018-02-13-07-00-12](https://user-images.githubusercontent.com/15039983/36148886-91b1d8ae-108b-11e8-8458-15f72adc6bde.png)

---

Instance: Mastodon.technology

Mastalab version: 1.7.9

Android version: 6.0

**Comment by stom79** [comment]
Yes. It has been fixed. See: https://github.com/stom79/mastalab/issues/317#issuecomment-365181150
