### ISSUE TITLE
Displays Username(s) in Bio as Plain Text

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#32]
If I add the full address of an account in the bio, Mastalab displays it only as plain text. Please make it so that upon tapping the link, the profile opens in the app itself.

Thanks.

**Comment by stom79** [comment]
It's not an easy matter. These accounts are returned in plain text with no [mention](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#mention). But I have a small idea on how to do.

**Comment by stom79** [comment]
Ok. It will be in the next release.
