### ISSUE TITLE
Unable to authenticate/log in

### ISSUE THREAD

**Issue by 1ZachM** [stom79/mastalab#321]
---

Instance: freehold.earth

Mastalab version: 1.7.9.1 and the 2 previous version

Android version: 8.1.0

**Comment by stom79** [comment]
Do you get an error message? Does the login button remain disabled?

**Comment by 1ZachM** [comment]
https://youtu.be/AG59rZh6oKI shows what happens

**Comment by stom79** [comment]
Weird. 2FA sounds to be broken. Do you get the same result by using the web interface?

**Comment by 1ZachM** [comment]
No problems on web or other apps.

**Comment by stom79** [comment]
OK. It works for me but I noticed a message at 1:08

> No matching item found in **Enpass** for gouv.fr

It sounds to be related to [another app](https://www.enpass.io/apps/android/) trying to take the hand on the authentication. Isn't it?

**Comment by 1ZachM** [comment]
I thought about that also and did try logging in with Enpass app disabled.
Same outcome. Enpass app always says that because I don't tie them to
specific apps. Always copy and paste from Enpass into fields manually.

Using Enpass to log in on web and another app also works fine.

**Comment by stom79** [comment]
For what I understand (I don't use Enpass), this app detects the authentication URL used by the built-in browser (that might have been recorded in Enpass when using another browser), and it doesn't find Mastalab in its entries for this URL (though I have a doubt concerning the interpretation of the app's id). Can you remove this URL in Enpass for tests?

**Comment by 1ZachM** [comment]
Just tried with the URL deleted and autofill turned off in Enpass. Same
problem. Restarted phone, force closed Enpass, manual copy and paste from a
saved note, same problem. Tried it from a Nexus 9 (LTE) without Enpass
installed, same problem.

Btw, main phone I have been working from is a stock, unrooted, Pixel XL
Android 8.1.0

On Feb 16, 2018 2:00 AM, "Thomas" <notifications@github.com> wrote:

For what I understand (I don't use Enpass), this app detects the
authentication URL used by the built-in browser (that might have been
recorded in Enpass when using another browser), and it doesn't find
Mastalab in its entries for this URL (though I have a doubt concerning the
interpretation of the app's id). Can you remove this URL in Enpass for
tests?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stom79/mastalab/issues/321#issuecomment-366167507>, or mute
the thread

**Comment by stom79** [comment]
But you shouldn't get the same error which was:

> No matching item found in Enpass for gouv.fr

Can you tell me the new error message?

**Comment by 1ZachM** [comment]
Sorry, I left that out. No error messages after turning off autofill and
all subsequent tries.

Same problem was not authenticating/log in just as before. Just without the
toast message.

**Comment by stom79** [comment]
I tested on 8.1.0 and there is no issue.
The proxy is not enabled? (3 vertical dots -> Proxy)

**Comment by stom79** [comment]
I will add custom tabs for login acitivty. It will allow to use a different browser.

**Comment by 1ZachM** [comment]
I do have a rooted Nexus 6 if you need anything else on my end. I'd be
willing to run a log cat or something tomorrow. About to go to bed in a
few. Just let me know.

**Comment by 1ZachM** [comment]
Sorry never answe4ed your last question. No proxy enabled.

New news: Tusky app signed in and working, but now web login says my
credentials are wrong. Haven't received an email back yet for a password
reset as if my email address is not in their system anymore.

**Comment by stom79** [comment]
Could you test [this apk](https://github.com/stom79/mastalab/blob/9a7f911989958135b8cdfb868079461df97be881/app/playstore/release/app-playstore-release-login-ct.apk?raw=true)? You have to check "custom tabs" in the menu.
