### ISSUE TITLE
Sideways Vertical Images

### ISSUE THREAD

**Issue by Fidgetcetera** [stom79/mastalab#330]
When uploading an image which has a "vertical" orientation, that is, the height is longer than the width, the image is rotated 90 degrees to be horizontal.

---

Instance: Sins.center (probably doesn't matter)

Mastalab version: 1.8.1

Android version: 7.0

**Comment by stom79** [comment]
I didn't get this issue. Example with a recent message: https://mastodon.social/@tom79/99541480825017676
Could you post an example?

**Comment by Fidgetcetera** [comment]
https://sins.center/@Fidgetcetera/99543034278136765 Here's an example.

**Comment by stom79** [comment]
Sorry but I can't reproduce that bug - I tried images from the gallery and others with the camera. Does this happen each time?

**Comment by Fidgetcetera** [comment]
Yep, every single time I try to post a vertical image I've taken. It's a galaxy s7 if that helps? I can try to test with similar images downloaded rather than taken from my camera roll.

If it helps, this seems to have only started happening after the update where image resizing was added - however, turning that off doesn't change things.

**Comment by Fidgetcetera** [comment]
Update: I think I've pinpointed the issue a bit more. I think it's not inherently vertical images, but the resolution my phone takes them at.  My phone will only take 16:9 images at 2592x1458 resolution or higher, and I suspect that somehow it's the large resolution that's causing the rotation somehow.

**Comment by jpdeplaix** [comment]
I second this; I have got the same issue.

**Comment by jpdeplaix** [comment]
@stom79 @Fidgetcetera What camera app do you use ? I use the default camera app from LineageOS (that should be close to stock android I suppose).
I've noticed that once opened using Gimp it asked if I wanted to keep rotation or not. So it might be an issue with a metadata that is not took into account.

**Comment by Fidgetcetera** [comment]
I use the stock Samsung one with my Galaxy S7. A friend did mention it might be rotation Exif data that's getting stripped?

**Comment by jpdeplaix** [comment]
It's getting really annoying. I have to rotate the image twice to get it to work. (because my image gallery app knows if I just done a 360 rotation)

**Comment by stom79** [comment]
@Fidgetcetera can you make a test after disabling the resize feature in settings?

**Comment by jpdeplaix** [comment]
@stom79 mmh I'm using 1.8.3 and disabling the resize feature doesn't help :/

**Comment by Fidgetcetera** [comment]
@stom79 Resizing doesn't help, and I do not get this with other apps.

**Comment by wintersyndicalist** [comment]
I can confirm that this is still a bug. I am using mastalab on a Galaxy S7.

**Comment by kit-ty-kate** [comment]
I can confirm, I'm using an ASUS Z00A

**Comment by kit-ty-kate** [comment]
Using ```mat``` (https://mat.boum.org/) I was able to identify a difference in the metadata before an after manual rotation (personal workaround):
```
-	Orientation: Rotate 90 CW
+	Orientation: Horizontal (normal)
```
I don't know how it translates into the code of the app or whether it's that and not something-else in the file (rotations change the file entirely not just the metadata), but that just my 2cts.

**Comment by stom79** [comment]
Hi there,
Could you test the apk and tell me if it fixes the issue with the rotation? Thanks.
https://github.com/stom79/mastalab/blob/fa3023aa737eae579d1bf6653a23a5bea1d43a7e/app/fdroid/release/app-fdroid-release-uploadFix.apk?raw=true

**Comment by Fidgetcetera** [comment]
@stom79 That seems to fix it!!!

**Comment by stom79** [comment]
Also, could test with and without image resizing.

**Comment by kit-ty-kate** [comment]
> It sounds it works when resizing is off

Just tested and I second that. It's going to the good direction at least. Thanks ! :)

**Comment by Fidgetcetera** [comment]
I'm finding it working with both resizing on and off both on the test APK.

**Comment by stom79** [comment]
@Fidgetcetera It would be a good news! I got this information from someone on Mastodon.
@kit-ty-kate Could you test also with and without resizing? Thanks

**Comment by kit-ty-kate** [comment]
@stom79 That's what I just said by approving what you were just saying:
* with resizing on it doesn't work
* with resizing off it works (where it didn't previously)

**Comment by stom79** [comment]
OK sorry. I will continue to investigate.

**Comment by stom79** [comment]
Could you test this apk, and check if now it work when resizing is enabled?
https://github.com/stom79/mastalab/blob/2793fa0f45c5dbf0efd4581fecddd7259fbe927f/app/fdroid/release/app-fdroid-release-uploadFix2.apk?raw=true

**Comment by kit-ty-kate** [comment]
@stom79 I can confirm that it works pretty well with resizing = No, 512k, 1M, 2M !! Thanks !

**Comment by Fidgetcetera** [comment]
@stom79 Tested as well, the images do not rotate in any resizing setting! Thank you so much!

**Comment by stom79** [comment]
Great! Thanks for testing.
