### ISSUE TITLE
replies to public posts are set to public privacy

### ISSUE THREAD

**Issue by clqn** [stom79/mastalab#331]
when replying to a public post, your reply is now set to public by default. this is incorrect behavior and only started appearing in the latest version; for correct behavior, look to the standard Mastodon implementation, where if your default post privacy is private, your replies to public posts will be private

**Comment by stom79** [comment]
Solved - duplicate with #329

**Comment by stom79** [comment]
Can you test [this apk](https://github.com/stom79/mastalab/blob/26a3be8650ebc0c35ea3bac71e8beebbd3da6ef4/app/playstore/release/app-playstore-release-1.8.2.apk?raw=true). Thanks
