### ISSUE TITLE
Error notifications stack endlessly when instance is down

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#338]
This happens due to the search-while-typing of hashtags. 

To reproduce: 

1. Start composing a toot on an instance which is down
2. type some hashtags in it
3. Dozens of "oops! An error occurred" notifications stack and keep playing long after you are trying to do something else 

This isn't the only example of too many error notifications stacking in the app, but it is the biggest I've yet found. 

---

Mastalab version: 1.8.1

Android version: 7.1.2

**Comment by stom79** [comment]
//TODO: Removes Toast messages

https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/activities/TootActivity.java#L1748
https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/activities/TootActivity.java#L1642
