### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by papppyo** [stom79/mastalab#347]
#### Expected behavior
I should be able to login and make use of the app

#### Actual behavior

I was unable to login,login button won't just respond and each time I input my instance ,i get an error saying "invalid host"
For a minute I  thought I didn't  register my instance account correctly so i had to troubleshoot by creating another email account to create another instance account to be sure I registered correctly 
When you check my recording of the bug you'll see I used two Instance account

#### How to reproduce

1.Download and install 

2.Launch

3.if you have an instance account  ,input it and  go to the next bar  you'll get an error ,and if you don't have one register here https://www.google.com.ng/url?sa=t&source=web&rct=j&url=https://mastodon.social/&ved=2ahUKEwjj2L-v3dXZAhWFvBQKHUkjDP0QFjAAegQICBAB&usg=AOvVaw0yPGDsUcRh25-Gge3l2PWB
Input your email address and passoword then click login 

4.Finally click the 3vertical dots by the left top corner and click about ,you'll should get a continuous message saying "error"

* Browser: mastalab 1.8.3

* Operating system: android 7.0 nougat 

#### Recording Of The Bug
https://youtu.be/_cPWZ9PnjZM

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@pappy/unable-to-login">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stom79** [comment]
Thank you for sharing your issue.
In the first field, you need to write "mastodon.social", if you use your screen name before, it will not work.
It's not related to the app but how mastodon works. You can take a look at https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/FAQ.md
