### ISSUE TITLE
2FA link missing

### ISSUE THREAD

**Issue by neonmoe** [stom79/mastalab#348]
When I first installed the app and opened it, the 2FA link was missing. After a restart, it appeared, however.

---
Instance: moe.neon.moe
Mastalab version: 1.8.3 or 1.8.2, the bug happened a while back.
Android version: 8.0.0

**Comment by stom79** [comment]
Thank you for creating this issue. The 2FA link should be displayed once the client id is retrieved, that means after filling the instance name, the login button should be enabled and the link should be displayed.
Could you try to add your account (it's not a problem for the app):
- Open the drawer menu
- Click on your screen name
- Add an account

Can you see the button enabled and the link at the bottom after filling the instance name with "moe.neon.moe"?

**Comment by neonmoe** [comment]
It seems to appear whenever I move the cursor out of the "instance" field, ie. click on another text field. At least imo it should appear without needing to do this, since at least I didn't realize it when I first tried to login.

**Comment by stom79** [comment]
Yes, but after filling the instance name, you need to fill the login field, so the focus will be automatically lost. I think the main problem is to make the 2FA link more visible.
