### ISSUE TITLE
Mastalab crashes on unexpected version string

### ISSUE THREAD

**Issue by lambadalambda** [stom79/mastalab#349]
Logging in on a Pleroma instance, Mastalab crashes while trying to compare versions.

See https://pleroma.soykaf.com/api/v1/instance.

---

Instance: pleroma.soykaf.com

Mastalab version: 1.8.3

Android version:

**Comment by stom79** [comment]
Could you bring more details: What steps make the app crash?

**Comment by stom79** [comment]
Does "Pleroma" word will be injected in every of its versions? If yes, I will activate all features as soon as the app will find it in a version name for an instance.

**Comment by lambadalambda** [comment]
Yes, it will always be there.

**Comment by stom79** [comment]
Does Pleroma has some specificities, especially concerning the "accounts/relationships" endpoint? I got some errors.

**Comment by stom79** [comment]
It sounds that it tries to read images from another server throwing 404:  https://ketsuben.red/media/....05FEC0A1E3577BA.png
The URL was voluntary truncated but the host was not changed.

**Comment by lambadalambda** [comment]
That's because we don't cache other users' avatars. this will change in the future, though.
