### ISSUE TITLE
there is a error when share to mastlab!

### ISSUE THREAD

**Issue by foxinstone** [stom79/mastalab#351]
when i share to masalab from NYTimes, will be a lot of code,and display nothing.

---

Instance:

Mastalab version:

Android version:

**Comment by stom79** [comment]
I can't reproduce that bug. I will need the instance name and the Android version.

**Comment by foxinstone** [comment]
Hi：
Because the Chinese nytimes was blocked by government, so, I can"t show
that error now. But , the RFI share to mastalab is same bug. Please see the
image,the last image is in RFI App. And my phone is Android  6.0, mastalab
is 1.8.3.


Thomas <notifications@github.com> 于 2018年3月14日周三 00:55写道：

**Comment by foxinstone** [comment]
Hi:
The instance is www.freechinaweibo.com.


Thomas <notifications@github.com> 于 2018年3月14日周三 00:55写道：

**Comment by foxinstone** [comment]
And, the VOA app also ...
Maybe about Chinese language?

Thomas <notifications@github.com> 于 2018年3月14日周三 00:55写道：

**Comment by stom79** [comment]
I tested to share an article from the bbc.com in Chinese language. I didn't get any errors. The title, the summary and the attached media were imported correctly. The bug is not due to Chinese language. I will continue to investigate, but a screenshot will help me :)

**Comment by foxinstone** [comment]
By the way, the Chinese XML is very  terrible,for example, the 'home' was
translated into 'family', the 'boost' was translated into 'Mute'...
Maybe you need a new translattor.

2018年3月14日 00:55，"Thomas" <notifications@github.com>写道：

I can't reproduce that bug. I will need the instance name and the Android
version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stom79/mastalab/issues/351#issuecomment-372738306>, or mute
the thread

**Comment by foxinstone** [comment]
I already sent three screenshots to you.

Thomas <notifications@github.com> 于 2018年3月14日周三 01:25写道：

**Comment by stom79** [comment]
That's bad... Thank you for warning me. Contributors use [Crowdin](https://crowdin.com/project/mastalab).

There is also something I don't clearly understand because It seems they are rewarded. I don't clearly understand how works this site [with the app](https://utopian.io/project/stom79/mastalab/github/107884371/all). But it seems to help to find contributors. I never asked for help or registered the app on that site though.

The Chinese contribution is here:
https://utopian.io/utopian-io/@sunray/traditional-chinese-translation-part-1-for-mastalab

**Comment by stom79** [comment]
> I already sent three screenshots to you.

OK, but it seems they are discarded when replying by email :(

**Comment by foxinstone** [comment]
Send again.

Thomas <notifications@github.com> 于 2018年3月14日周三 01:40写道：

**Comment by stom79** [comment]
At the bottom of the mail, click on "View it on Github", you will see that the current thread didn't collect the screenshots. You have no choice than to add them manually via github.

**Comment by foxinstone** [comment]
My god, I can not paste them into here, Or ,give me a email address?

**Comment by foxinstone** [comment]
Please wait while, i try this On my PC again.

**Comment by foxinstone** [comment]
first screenshot is in RFI 
![image](https://user-images.githubusercontent.com/35874666/37360633-cd94b696-272b-11e8-8a55-d40669f59c1d.png)

**Comment by foxinstone** [comment]
the second screenshot:
![image](https://user-images.githubusercontent.com/35874666/37360730-03b1478a-272c-11e8-9983-8bf9699af386.png)

**Comment by foxinstone** [comment]
the third:
![image](https://user-images.githubusercontent.com/35874666/37360823-413b2ed6-272c-11e8-9290-931437bae517.png)

**Comment by stom79** [comment]
Oh ok! Chinese characters are returned in unicode!

**Comment by foxinstone** [comment]
i agree!

**Comment by stom79** [comment]
Thanks for reporting this bug. HTML content is now converted when metadata are retrieved. That should fix this bug.

**Comment by foxinstone** [comment]
i log in crowdin, but i can not see  simplified chinese, i think it need you add...

**Comment by stom79** [comment]
Yes. I got an issue, I need to do some changes but the best would be to use the file on github. It's no longer synchronized and it should not be overriden with changes.

**Comment by stom79** [comment]
If you want to contribute, I will check these elements and add them here.

**Comment by foxinstone** [comment]
Yes,I like that.

Thomas <notifications@github.com> 于 2018年3月14日周三 03:17写道：

**Comment by stom79** [comment]
See
