### ISSUE TITLE
Dispaying the current thread only

### ISSUE THREAD

**Issue by jpdeplaix** [stom79/mastalab#354]
Right now when displaying a thread, Mastalab is displaying every threads starting from the base toots as well. Is it possible to just display the current thread or if it's actually a feature, could we have a more clear view of which toots are responding to which ?

---

Mastalab version: 1.8.3

**Comment by stom79** [comment]
I agree. I introduced this feature few months ago and it should not be set as the default behavior. I will see if I remove it or if I introduce an expand button. But for sure, it will not be the default behavior in the next release.

**Comment by stom79** [comment]
I added an expand more/less icon in top bar. By default, only the context of the focused toot is retrieved (like it's done with the mastodon webapp). By clicking on this icon it expands the whole conversation and vice versa.

<img src="https://user-images.githubusercontent.com/30171182/37480120-b6a46f9a-287e-11e8-8fd1-aa762091a648.png" width=300/> <img src="https://user-images.githubusercontent.com/30171182/37480124-b836cbb4-287e-11e8-8d81-953680fefa4e.png" width=300/>
