### ISSUE TITLE
there is a new error when share to mastlab!

### ISSUE THREAD

**Issue by foxinstone** [stom79/mastalab#359]
When i sharing Chinese content from other app(eg. RFI or VOA)，I didn't touch anything.，it will be crash and exit.(popup dialog "sorry, mastalab Stopped running")
But when i sharing English content，it is ok.

---

Instance:www.freechinaweibo.com

Mastalab version: 1.8.4

Android version:6.0

**Comment by stom79** [comment]
OK. I guess it's due to the fix from #351

**Comment by foxinstone** [comment]
Sorry, i made a mistake.
In fact, Even sharing English content can make mistakes.

**Comment by stom79** [comment]
I switched into Chinese & caught this crash - it's fixed and content should be correctly extracted.
