### ISSUE TITLE
Add ability to disable bookmark function

### ISSUE THREAD

**Issue by beta-phenylethylamine** [stom79/mastalab#366]
Mastalab is easily my favorite mastodon app, but there's just one glaring thing that I really wish I could change, and that's the inclusion of the bookmark button on every toot. It tends to make toots taller than they need to be and, while I understand the draw for more extreme power users, I personally don't get much out of it and it greatly detracts from the aesthetics of the app.

Ideally, it would be possible to move it to the toot's menu popup, but there's no real elegant way to give that a setting so it'd probably make more sense to just be able to disable it (probably removing the sidebar tab for the bookmarks while you're at it I suppose)

**Comment by stom79** [comment]
Thanks for this suggestion. I added the ability to remove this button. Also, this feature has been added in the dropdown menu.
<img src="https://user-images.githubusercontent.com/30171182/37873663-af8a0c9c-3021-11e8-8a23-3ce087926342.png" width=300/> <img src="https://user-images.githubusercontent.com/30171182/37873664-afa62a94-3021-11e8-97ae-5966dc351f11.png" width=300/> <img src="https://user-images.githubusercontent.com/30171182/37873665-afc2580e-3021-11e8-9f7a-c7e140364b42.png" width=300/> <img src="https://user-images.githubusercontent.com/30171182/37873666-afdf1dc2-3021-11e8-819d-4aada2d7963c.png" width=300/>

**Comment by beta-phenylethylamine** [comment]
That's perfect, thank you!

**Comment by stom79** [comment]
You're welcome :)
