### ISSUE TITLE
Erreur lors du changement d'image de profil

### ISSUE THREAD

**Issue by Sim59121** [stom79/mastalab#369]
Bonjour,

Je voudrais changer mon image de profil mais je ne peut pas...

À chaque fois j'ai le message d'erreur "oupss une erreur s'est produite" qui apparaît...

Pourriez-vous m'aider svp ??
Cordialement 
---

Instance: social.bruniau.net 

Mastalab version: 1.8.4

Android version: 7.1.1

**Comment by Sim59121** [comment]
L'instance est social.bruniau.net

**Comment by stom79** [comment]
Je n'arrive pas à joindre cette instance. Pourriez-vous ouvrir le menu de gauche et cliquer sur le "i"? Cela donnera quelques infos sur l'instance et notamment si elle est down. Merci.

**Comment by Sim59121** [comment]
J'ai vérifié, elle n'est pas down et je n'arrive pas à voir les infos...
Cela charge à l'infini...

**Comment by Sim59121** [comment]
D'accord !!

Puis-je faire quelque chose pour vous aider ??

**Comment by stom79** [comment]
Pourriez-vous :

- Changer votre image de profil depuis cette instance ?
- Si cela fonctionne, il faudrait refaire le test avec la même image mais sur Mastalab.

En fonction du résultat, on pourra voir si cela vient de l'instance ou non.

**Comment by Sim59121** [comment]
Cela marche sur l'instance.
J'ai ré essayé sur mastalabe et ça ne marche pas. (Toujours le même message
d'erreur).

**Comment by stom79** [comment]
L'application a-t-elle les droits pour lire/écrire le contenu de la carte SD ? Normalement, elle demande cette autorisation. Si elle a été refusée, l'application ne peut pas fonctionner correctement pour le téléchargement/l'envoi des images.

**Comment by stom79** [comment]
Pour vérifier, il faut aller dans les paramètres du téléphone et choisir "Apps" ou "Applications". Ensuite, il faut sélectionner "Mastalab" dans la liste. Il devrait y avoir quelque chose comme "Autorisations", cliquez dessus. Vérifiez que "storage" ou "stockage" est bien sélectionné.

**Comment by Sim59121** [comment]
Oui, elle as l'autorisation

**Comment by stom79** [comment]
Est ce que vous voyez une petite fenêtre popup qui affiche votre profil? Cette popup est affichée une fois que vous cliquez sur le bouton enregistrer ? Ou le message s'affiche dès que vous sélectionnez une image ?

**Comment by stom79** [comment]
Le problème est lié à l'instance.  Par contre, il faut ajouter un message quand l'instance n'est pas listée sur instances.social cf: https://github.com/stom79/mastalab/issues/369#issuecomment-375978496
