### ISSUE TITLE
Option to close NSFW contents

### ISSUE THREAD

**Issue by gergelypolonkai** [stom79/mastalab#371]
When I open something NSFW and timeout is set to 0, there is no way to close it. Sometimes Iʼm in a situation when I can expand such content, but may want to close it a moment later.

---

Mastalab version: 1.8.4

Android version: 6.0.1

**Comment by stom79** [comment]
Thanks. I will add a button to hide the content like in the web app.

**Comment by gergelypolonkai** [comment]
Not to put stress on you, but with the [rise of switter](https://switter.at/users/switter/statuses/99782645726486994) this became a bigger issue I think.

**Comment by stom79** [comment]
I am sorry, I didn't have a lot of time currently :(
It's fixed and it will be in the next release.
