### ISSUE TITLE
Logging in problem

### ISSUE THREAD

**Issue by WilliamKnipe** [stom79/mastalab#374]
When I type the instance "mastodon.social" the auto complete mastodon.social pops up but when I click it it just immediately pops back up again. If I press enter/type in manually the following happens:

Trying to log in. Sometimes the button doesn't seem clickable. Other times  I click log in and then nothing happens apart from a small popup says "https://mastodon.social/oauth/token".  It disappears after a few seconds, nothing else happens. Just stuck on the first log in page.

I am a complete noob so I'm sorry if I am doing the wrong thing.

After entering 
---

Instance: mastadon.social

Mastalab version: 1.8.4

Android version: 6.0

**Comment by stom79** [comment]
Do you use 2FA? If yes, you need to click the link which is displayed once the instance is filled.
If you don't use 2FA it sounds there is an issue with your credentials. Could you test them in the webapp? Also, you can use the 2FA link even if you don't use 2FA, it will work :)
PS: login button is enabled once the client ID has been retrieved.

**Comment by WilliamKnipe** [comment]
haha I missed a character in my password :D I couldn't tell what was going on so thought it was possibly something going on with the app. 

I can log in now and it looks great :)

**Comment by stom79** [comment]
Great! If you have other issues let me know :)
