### ISSUE TITLE
Feature request: Show Images On Image Description Dialogue

### ISSUE THREAD

**Issue by Fidgetcetera** [stom79/mastalab#38]
Simple and sweet. If I'm describing an image I'd like to have the dialogue be below the image I'm trying to describe. Useful in general, but especially if the image contains a lot of text to transcribe to the description (eg, screenshotting this app's settings menu, screenshots of articles, pictures of handwriting...)

**Comment by stom79** [comment]
Available in [1.6.0-beta-2](https://github.com/stom79/mastalab/releases/tag/1.6.0-beta-2)
