### ISSUE TITLE
Video embed not displayed for YouTube mobile urls 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#386]
If a user shares a YouTube video from the mobile url, it's not displayed in the toot like usual. 

https://witches.town/users/Angle/statuses/99779476530229465

**Comment by stom79** [comment]
That's due to the CW. When a user decide to hide his/her toot with a content warning, there is no card associated to the toot. So, the app can't detect that a video URL is attached. I am sorry, but there is nothing to do on the application side.

**Comment by deutrino** [comment]
Oh, the cards are generated by mastodon itself?

**Comment by stom79** [comment]
Yes. You can get the card associated with  a toot by calling https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#getting-a-card-associated-with-a-status
