### ISSUE TITLE
Why don't you run repair on the sharing feature

### ISSUE THREAD

**Issue by foxinstone** [stom79/mastalab#387]
Some days ago, i reported the shared functionality bug on 1.8.4 version.
Why not upgrade solve it ? you know, cause for social software, this feature is very important !!!

---

Instance:www.freechinaweibo.com

Mastalab version:1.8.4

Android version:6.0

**Comment by stom79** [comment]
Yes, sorry. Please follow my account to see updates :)
https://mastodon.social/users/tom79/statuses/99783580744013924
I will publish this release today. I have less time recently to work on the app. So I solved the two most important points.

**Comment by stom79** [comment]
You can use the last release 1.8.5. I published it.
https://github.com/stom79/mastalab/releases/tag/1.8.5

**Comment by foxinstone** [comment]
Thanks for your work.

Thomas <notifications@github.com> 于 2018年4月2日周一 15:17写道：
