### ISSUE TITLE
Posting before attaching image is done without attatchment

### ISSUE THREAD

**Issue by sftblw** [stom79/mastalab#397]
Tooting immediately after selecting image and before fully uploaded does toot, but without attached image.

1. Write some text
2. Select image to attach
3. Before It's fully uploaded, quickly touch toot button
4. Check posted toot which does not contain image

---

Instance: [twingyeo.kr](https://twingyeo.kr)

Mastalab version: 1.8.5

Android version: 7.0 (Build NRD90U)

Device: LG G6 (LGM-G600K)

**Comment by stom79** [comment]
I disabled the toot button while a media is uploading
