### ISSUE TITLE
Problem with Scheduled Toots 

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#4]
Scheduled toots aren't sent on time. Before the latest update, Mastalab would send the scheduled toot a minuter later than the scheuled time but now it takes even more time!

**Comment by stom79** [comment]
I guess it comes from the update of a lib. How long it takes now? Is your battery saver enabled?

**Comment by iknownothingaboutcomputers** [comment]
Yes, battery saver was enabled at the time. IIRC, it took 8-10 minutes. I'll check again tomorrow and get back to you.

**Comment by stom79** [comment]
OK. There should be a message at the bottom of the activity to warn about battery saver. Also, I added a feature in the last release (1.5.4) which stops services from the app when battery is low.
