### ISSUE TITLE
"The app did not collect custom emojis for the moment"

### ISSUE THREAD

**Issue by jfmcbrayer** [stom79/mastalab#40]
This is the message given when I click the emoji button when composing a toot on glitch.social or anticapitalist.party. Not sure if the message means to imply that this is a feature that is planned but not yet implemented, or whether the app is supposed to be fetching custom emoji at runtime.

**Comment by stom79** [comment]
There is no feature to get custom emojis from an instance. So the app will "learn" from toots you read. If a custom emoji is displayed you should be able to reproduce it.
What you can do:

- Use the web UI from your instance
- Post a private toot with custom emojis
- Open Mastalab and read your toot

These custom emojis will now be displayed when writing a toot.

**Comment by stom79** [comment]
@jfmcbrayer is it ok for you? Can I close this issue?

**Comment by jfmcbrayer** [comment]
No, after posting a private post (DM to myself) containing all the custom emoji on my instance, and opening that toot with Mastalab, and trying to reply to it, I still get the same message. Sorry.

**Comment by stom79** [comment]
Are custom emoji correctly displayed on the app (in your private toot)?

**Comment by jfmcbrayer** [comment]
Yes, they are.

**Comment by jeroenpraat** [comment]
I can confirm this too. Whatever I do, no custom emojis available.

**Comment by stom79** [comment]
Ouch!! Ugly mistake. There was a missing table for fresh installations :(

**Comment by jfmcbrayer** [comment]
Can confirm this is fixed.
