### ISSUE TITLE
Adding an option to send photos as JPEG instead of PNG

### ISSUE THREAD

**Issue by Fabiensk** [stom79/mastalab#402]
From what I understand and tested, photos taken with the camera and sent are compressed in PNG. It would be more efficient to have an option to use JPEG instead (by default with 80% compression and progressive JPEG) which would be the default.

Instance: framapiaf.org, Mastodon 2.3.3

Mastalab version: 1.8.5 (f-droid)

Android version: 7.0

**Comment by stom79** [comment]
Thanks for catching this issue. It's fixed.
