### ISSUE TITLE
Confusing timer display

### ISSUE THREAD

**Issue by alanz** [stom79/mastalab#404]
The "My started games" screen presents a confusing countdown time.

![screenshot_20180415-201627](https://user-images.githubusercontent.com/409607/38781765-a91230ae-40ea-11e8-82af-13385b86b57e.jpg)

The game is of type "classical 1d", but the way the remaining time is appended, it looks like there is a day and 8 hrs remaining.

---

Instance:

Mastalab version: 292

Android version: 8.0.0

**Comment by stom79** [comment]
Not sure I can help here :) Funny, for the issue number 404 :)

**Comment by alanz** [comment]
Well, putting some kind of separator between the game type and time to go would help.

`Classical 1d : 8h, 1m `

Or right justify the time to go.

I guess it is innocuous, now that I have got over my initial confusion.

**Comment by stom79** [comment]
I would love to add these two dots as a separator. Unfortunately, I don't know where I can change this piece of code :)

**Comment by alanz** [comment]
Oh bugger, I just realised I am in completely the wrong repo.

No wonder you have no idea what I am talking about :)

Its probably because I like mastalab so much.

**Comment by stom79** [comment]
Thanks for supporting the app! I love that this ticket has the number 404 :)
