### ISSUE TITLE
duplicate toots in timeline

### ISSUE THREAD

**Issue by jfmcbrayer** [stom79/mastalab#41]
I often, but intermittently, see duplicate toots in my timeline. Generally, they are displayed next to each other. I have also seen them in my notifications.

**Comment by stom79** [comment]
Thanks for this report. Just to be sure, these duplicate toots are displayed twice, not more?

**Comment by jfmcbrayer** [comment]
I believe so. I am not 100% sure that I have not seen 3.

**Comment by jfmcbrayer** [comment]
If you've pushed this to Play Store beta channel, I am testing it now.

**Comment by jfmcbrayer** [comment]
If the version in the Play Store beta channel this morning has this commit, it's not working. I've seen duplicates (2) in my home feed, and in notifications, I got 5 copies of a reply.

**Comment by stom79** [comment]
@jfmcbrayer No it doesn't. I will publish the new one in few minutes. I was fixing some other bugs.

**Comment by jfmcbrayer** [comment]
Great, thanks.

**Comment by stom79** [comment]
OK, I added a fix in release [1.6.0-beta-2](https://github.com/stom79/mastalab/releases/tag/1.6.0-beta-2).

Did this issue happen only with the beta release (which works with live notifications)?

**Comment by jfmcbrayer** [comment]
I don't know, I've only used the beta.

**Comment by jfmcbrayer** [comment]
On the new one, I just saw a duplicated boost on my home timeline.

**Comment by stom79** [comment]
Thanks for the feedback. It is one too many... I will continue to investigate with boosts.

**Comment by jfmcbrayer** [comment]
I am very sorry to spam you with so many bug report updates. I just saw a duplicate (non-boost) in my home timeline. Interestingly, they were listed as about 13 minutes apart.

**Comment by stom79** [comment]
OK. Thanks for the feedback. I will try to catch this bug. I think it's a problem between new toots coming from the streaming API and missing toots that are retrieved. I might have missed a control somewhere to avoid that.

**Comment by stom79** [comment]
OK. I found something that can explain these duplicate toots. I pushed in the beta channel the [third release](https://github.com/stom79/mastalab/releases/tag/1.6.0-beta-3). It will also solve issue #40

**Comment by stom79** [comment]
@jfmcbrayer @jeroenpraat  Did you notice some improvements? (I just pushed 1.6.0-beta-4). Thanks

**Comment by jfmcbrayer** [comment]
This appears to be fixed.

**Comment by jeroenpraat** [comment]
For me too. Thanks!

**Comment by stom79** [comment]
Thanks for your feedback.
