### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by guland2000** [stom79/mastalab#410]
Russian language wanted, how to help?! Make in string or something else?

---

Instance:

Mastalab version:

Android version:

**Comment by stom79** [comment]
Thanks for your suggestion. Mastalab works with Crowdin for localizations. You need an account and you can contribute here:
https://crowdin.com/project/mastalab

**Comment by guland2000** [comment]
So Russian 100% is done. Only one thing i did not translate a word **Toot**, let it as original. Maybe in future will do some thing with that. (I looked at the discussion about this word ...
It can not be translated only if the language is based on Latin.
But it will have to be translated in case it's Cyrillic (in my case Russian and other Slavic languages). The same is the case with Chinese, Arabic, etc. languages.)
It's funny but in translation it should sound like a voice / growl / roar / roar of an elephant of a relative of a mastodon ... It's not tweet but something more overweight and having the power of alerting.

Other word: **instance** here everything is simpler and i translated it as a **Server** ...

So ... In the future, **edits are possible based on the context**. Now the general picture is not yet very clearly visible, you just need to start the translation and maybe something to fix it.
