### ISSUE TITLE
Scrolling issues 

### ISSUE THREAD

**Issue by CimsonTentacles** [stom79/mastalab#42]
Sometimes while scrolling the feed it jumps back up and refuses to be pulled down for a few seconds.

**Comment by stom79** [comment]
Thanks for the report. Does it happen in a particular timeline (Home/ Locale / Public)? Also, does it happen when you start scrolling (ie: beginning of the timeline) ?

**Comment by CimsonTentacles** [comment]
It happens on all timelines equally, also on user pages. And I think the beginning of timeline is slightly more affected, but it happened somewhere in the middle too

**Comment by stom79** [comment]
Could you tell me if it's better with the last release [1.6.0] (https://github.com/stom79/mastalab/releases/tag/1.6.0) (which will be in prod soon).

**Comment by foxmask** [comment]
i met this behavior on the user timeline

**Comment by stom79** [comment]
@foxmask 
Could you please tell me:
- What Android version do you use?
- Does this bug still happen with last release?
- Does it happen when doing something particular: opening a media/ using the translation / clicking on spoilers, etc.? 
- When it happens, do you notice a new toot has been displayed in your timeline?

**Comment by foxmask** [comment]
* What Android version do you use?
7.1.1
* Does this bug still happen with last release?
i didnt try it yet
* Does it happen when doing something particular: opening a media/ using the translation / clicking on spoilers, etc.?
i'm scrolling from a tooter page
* When it happens, do you notice a new toot has been displayed in your timeline?
that may happened but not each time

**Comment by foxmask** [comment]
1.6.0 tested and same thin
