### ISSUE TITLE
Clicking to another toot in conversation mode doesn't fetch its children

### ISSUE THREAD

**Issue by kit-ty-kate** [stom79/mastalab#421]
Since #354 the way conversations are displayed changed. However inside a thread, clicking on another toot/root doesn't change the the view according to the new "root toot".
Can we have something like this ?

---

Mastalab version: 1.8.6

**Comment by stom79** [comment]
OK. It's time to work on this ticket and #346

**Comment by stom79** [comment]
It should be better for this part.

**Comment by kit-ty-kate** [comment]
Thanks ! :)
