### ISSUE TITLE
Add filtering option for columns

### ISSUE THREAD

**Issue by jeroenpraat** [stom79/mastalab#43]
In Mastodon's webapp you can filter out words and hashtags in a column/timeline, like this

pineapple|#trump|soccer

It would be usefull to have this in Mastalab too. I suggest using the long touch on the column icon (like other column options).

**Comment by stom79** [comment]
@jeroenpraat I planned to do that, but I didn't take the time to see how it works. It's about regex, but when I used it on the web UI, I didn't manage to understand how it works. I put my regex and I got results that should have been filtered.

**Comment by jeroenpraat** [comment]
I think it's a very basic regex. I only can add words separated by a |. So when you know that, it's very powerful.

**Comment by stom79** [comment]
@jeroenpraat OK. Could you please test this [release](https://github.com/stom79/mastalab/blob/21ad71a3e63bc0a74adfa034ab86100652164c9b/app/safetynet/release/app-safetynet-release-filters.apk?raw=true).

You should be able to filter with regex on the three timelines.

**Comment by jeroenpraat** [comment]
Works great! I even see you copied and pasted the right translations. 

Thanks!

**Comment by stom79** [comment]
Great. I improved filters, regex are not longer case sensitive.
