### ISSUE TITLE
Mastalab uses too much data

### ISSUE THREAD

**Issue by JaapD** [stom79/mastalab#431]
I installed version 1.8.7.1, after that, mastalab uses more than 900 Mb of my data. Previous versions did not even use 10Mb in a few days. I did not download much pictures or other large files.

---
Instance:

Mastalab version: Version 1.8.7.1

Android version: 7.1.2 and LinageOS 14.1-20180428-NIGHTLY-onyx

**Comment by stom79** [comment]
Did you try to clear the cache from the app? Open the left menu, click on the three dots then "clear cache". Also what size Mastalab detects for the cache?

**Comment by stom79** [comment]
Even if you download nothing from yourself, the app will cache pictures and videos. I will add an automatic cache cleaning. I will try to make it cleaver, for cleaning old content first.

**Comment by stom79** [comment]
I will close this issue, let me know if you need more info.

**Comment by JaapD** [comment]
After more than 2 months, the problem did not return. I use Mastalab rather often.
