### ISSUE TITLE
Instance doesn't appear on the dropdown menu

### ISSUE THREAD

**Issue by ardydo** [stom79/mastalab#44]
I've read issue #37 but that seems different so I'm opening a new one. If this is wrong just wipe it away.

I'm trying to login into masto.donte.com.br but it keeps giving "unable to get client!" errors. I checked the other login issue and it seems like I can't login if the instance doesn't appear on the dropdown menu and masto.donte.com.br doesn't actually shows up. I've successfully logged in other instances (and logged in this instance using another app) so I think the problem really lies somewhere in mastalab.

If it does matter, I'm running mastalab 1.5.7 from f-droid on a rootless LG-K42017 that runs Android 6.0

**Comment by stom79** [comment]
I am able to get the client id for `masto.donte.com.br`. If nothing is displayed, it might be related to `instances.social` API which is down or the instance `masto.donte.com.br` which was down during your tests.
But what you said is interesting, I will have a look to the consequences if `instances.social` API is down when retrieving the client id.

**Comment by stom79** [comment]
OK, I get this error:

> SSL handshake aborted: ssl=0xf38da0c0: Failure in SSL library, usually a protocol error
>                                                                        error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (third_party/openssl/boringssl/src/ssl/tls_record.cc:575 0xd72793c0:0x00000001)
>                                                                        error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (third_party/openssl/boringssl/src/ssl/handshake_client.cc:885 0xd9c31ba8:0x00000000)

**Comment by stom79** [comment]
Could you please check if it's fixed in [1.6.0-rc-1](https://github.com/stom79/mastalab/releases/tag/1.6.0-rc-1). APKs can be downloaded on this page.
