### ISSUE TITLE
Home timeline freezes on a specific toot.

### ISSUE THREAD

**Issue by gergelypolonkai** [stom79/mastalab#445]
Mastalab freezes when trying to display a specific toot. Even force closing doesnʼt work, as it opens on the last viewable toot and freezes again when I try to scroll up.

Instance: social.polonkai.eu

Mastalab version: 1.8.8

Android version: 6.0.1

**Comment by stom79** [comment]
If it's a public toot, could you copy/past its URL?

**Comment by gergelypolonkai** [comment]
I actually did, it seems I deleted it with one of the answer placeholders…

Most probably itʼs [this one](https://social.polonkai.eu/web/statuses/99989548989283648)

**Comment by stom79** [comment]
The bug will be fixed in the next release
