### ISSUE TITLE
Content Warnings are not displayed on boosted toots

### ISSUE THREAD

**Issue by Aldarone** [stom79/mastalab#45]
When someone boost a toot with a content warning, the label of the content warning is not displayed : 

Original toot : 
![img_20171116_132641](https://user-images.githubusercontent.com/2682011/32891206-04852f5c-cad2-11e7-8484-0bfeebbfae20.jpg)

Same toot but boosted by someone : 
![img_20171116_132553](https://user-images.githubusercontent.com/2682011/32891238-192ca944-cad2-11e7-91d1-0b43dae8df1c.jpg)

I use the v1.6.0b1

**Comment by stom79** [comment]
Thank you for this report! It's fixed.
