### ISSUE TITLE
Selecting text and then scrolling crashes the app

### ISSUE THREAD

**Issue by gergelypolonkai** [stom79/mastalab#450]
When I select some text (eg. by long pressing on a word) and then scroll, the app crashes. I can only reproduce it by scrolling up (ie. towards newer toots), but Iʼm pretty sure it happened in the other direction, too.

---

Instance: social.polonkai.eu 

Mastalab version: 1.8.9

Android version: 6.0.1

**Comment by stom79** [comment]
I tried to reproduce that bug but I didn't manage. It will need more investigations.

**Comment by gergelypolonkai** [comment]
Tell me if I can help with anything, like with a debug version or something…

**Comment by stom79** [comment]
I caught it. It was due to an IndexOutOfBoundsException.
