### ISSUE TITLE
Allow to boost/fav/reply from another account

### ISSUE THREAD

**Issue by allo-** [stom79/mastalab#485]
It would be a nice feature to be able to interact with a toot from another account.

A useful scenario is having an account on a instance which fits you and an account on a larger instance to have a better local and federated timeline.
Then it is complicated to interact from another account. The easiest workflow currently seems  to be "mention -> copy the url -> switch the account -> search the url -> interact with the toot".

The reply function could have an account chooser at your profile image at the top, for boosts and favs there could be a small arrow next to the icon and for boosting with the confirmation dialog there could be the possiblity to switch the account in the dialog as well.

**Comment by stom79** [comment]
You just need to long press the reply, boost or fav button. Then you will be able to pick up the account.

**Comment by allo-** [comment]
Ok, thank you.
