### ISSUE TITLE
"Unable to client id!" on masto.donte.com.br using Android 6

### ISSUE THREAD

**Issue by renatolond** [stom79/mastalab#50]
Hi!
I had some users complaining that they can't use mastalab with masto.donte.com.br, I have an android running 7.1.1 and it runs with no issues, but today I tried using my old android, running 6.0.1 and I keep getting "unable to get client id" when trying to choose the instance. I tried some other instances in the list and didn't saw any trouble with them.

**Comment by stom79** [comment]
Hi.
I have been warned about this issue which was due to a lib. So I built my own logic and I removed this library.
The fix can be downloaded here :
https://github.com/stom79/mastalab/releases/tag/1.6.0
There are some edge effects on some instances (upload issue) but I am working on.

**Comment by renatolond** [comment]
Thanks for the prompt response :) Sorry, I didn't saw that those issues were related.
I tried the new build and it worked like a charm (media upload also worked).

**Comment by stom79** [comment]
@renatolond You're welcome and thanks for your feedback. As soon as the remaining issue with upload will be fixed, I will publish it in prod (currently available on the  beta channel  and soon on Fdroid)
