### ISSUE TITLE
Button "Skip to first unread Message"

### ISSUE THREAD

**Issue by JonasDralle** [stom79/mastalab#503]
Many twitter refugees were used to reading the micro messages FIFO.
Is it possible to have a button that is visible after a refresh that upon pressing scrolls down to the first new message?

Maybe hide the button when the user starts scrolling.

**Comment by stom79** [comment]
I am not sure to understand. When opening the app, it remembers your last position in the TL. So new messages are above and by tapping the tab, it will scroll up to the last messages.

**Comment by JonasDralle** [comment]
Yeah you're right. I think this was an issue with my usage of the drag-to-refresh feature, sorry.
