### ISSUE TITLE
"Show less" does not work when "Display hidden content auto" enabled

### ISSUE THREAD

**Issue by nicofrand** [stom79/mastalab#508]
Hi, 

I'd like to thank you for this nice app first!

**STR**:

1. In the parameters enable "Display hidden content automatically" ("Afficher automatiquement le contenu masqué" in French)
1. Go to your timeline

**What happens:**

The toots hidden content appear as expected but there is still a "Display less" text (like when this parameter is disabled and you clicked on the "Display more" to bypass the content warning.
This text is not clickable (it does not hide the content behind the content warning)

**What I expect:**

"Display less" ("Afficher moins…" in French) is not displayed.

---

Instance: mastodon.social

Mastalab version: 1.15.2

Android version: 8.1.0

**Comment by stom79** [comment]
Please, address this issue on gitlab. I can't reference it in commit otherwise.

**Comment by nicofrand** [comment]
Sorry about that, I did not see the project was moved to gitlab. I created a new issue: https://gitlab.com/tom79/mastalab/issues/517
