### ISSUE TITLE
FR: Sharing intent should be properly handled.

### ISSUE THREAD

**Issue by blinks** [stom79/mastalab#54]
I'd like to share to Mastadon from other apps on Android, but the sharing intent (in this case, from BG Stats with an image and text) doesn't do anything but open the app.

**Comment by stom79** [comment]
What release do you use? Is it related to #53 ?
When sharing from other apps, the app picks up the title/summary/picture (when available).

**Comment by blinks** [comment]
This is on 1.6.1, and I don't get a crash -- it just opens the app.  I don't even get a new toot to edit.

**Comment by stom79** [comment]
OK. So I will need examples of content that doesn't work and also your Android version.

Currently, the app gathers some properties in the html page: 

```
meta[property=og:title]
meta[property=og:description]
meta[property=og:image]
```

I guess I need to extend this part with information you will give me.

**Comment by stom79** [comment]
Fixed in https://github.com/stom79/mastalab/releases/tag/1.6.4
