### ISSUE TITLE
No toots showing and when I log out, could not possible to login in back

### ISSUE THREAD

**Issue by ovocie** [stom79/mastalab#58]
... when I click on my profile, app shuts down.
I tried everything: log out, log in, reinstal app. It looks like the login button is inactive.

**Comment by stom79** [comment]
Thanks for this report. Could you tell what instance do you use? I will check what happens.

**Comment by ovocie** [comment]
mastodon.social

**Comment by ovocie** [comment]
It's working!

**Comment by stom79** [comment]
In the last release I added a better control with network issues. This [release](https://github.com/stom79/mastalab/releases/tag/1.6.2-beta-1) handles some other errors and avoid crashes.

**Comment by stom79** [comment]
Release 1.6.2 brings more features to avoid this behavior.
