### ISSUE TITLE
Prevent the loss of privacy when replying to a toot. 

### ISSUE THREAD

**Issue by Aldarone** [stom79/mastalab#59]
Currently Mastalab always use the same visibility level for the replying toot as the replied toot. 

This is not on par with what the web client does and can result in a loss of privacy for the user.

For example :

- Default privacy is "***unlisted***", original toot privacy is "***private***" ▶️ The privacy of the reply is "***private***" in Mastalab and the web client. 👍 
- Default privacy is "***private***", original toot privacy is "***public***" ▶️ The privacy of the reply is ***"private" on the web client*** but ***"public" on Mastalab***. 👎 

The second case is confusing because the web client ensures that the privacy is always the higher choice between original toot privacy (defined by another person) and default privacy (defined by the user) but in this case Mastalab does not respects the user defined privacy and always fallback to the other person choice.

**Comment by stom79** [comment]
When the privacy of the account is private, this problem does not occur. It only occurs when the default privacy *is set inside the app*. The API does not allow to change this level of privacy. So, it's better to define the level of privacy with the web app to get "real" private accounts.
I will improve that point, though people switching from an app to another might be lost?

**Comment by Aldarone** [comment]
I just tried and the behaviour of the web client doesn't change with the protected/unprotected status of the account : It always keep the higher privacy between the default setting or the replied toot setting.

I'm aware that there is no api endpoint to set nor get default privacy so it must still be per client, but I do think it'd be better if third party clients could align their behaviour with the web client which is the reference implementation.

**Comment by stom79** [comment]
>  but I do think it'd be better if third party clients could align their behaviour with the web client which is the reference implementation.

You are absolutely right.

> I just tried and the behaviour of the web client doesn't change with the protected/unprotected status of the account

Did you restart the app? Do you see a new menu item concerning follow requests?

**Comment by Aldarone** [comment]
> Did you restart the app? Do you see a new menu item concerning follow requests?

Yes and yes

**Comment by stom79** [comment]
I don't manage to reproduce this bug.

I locked one of my accounts (sorry it's in french):
<img src="https://user-images.githubusercontent.com/30171182/33230465-21ed5218-d1e4-11e7-9612-cf4c982a435e.png" width=400/>

I restarted the app and saw follow requests item (like you had):
<img src="https://user-images.githubusercontent.com/30171182/33230466-248bf4d4-d1e4-11e7-9392-19a133e5713f.png" width=300/>

I selected a public message to reply:
<img src="https://user-images.githubusercontent.com/30171182/33230468-278ec68e-d1e4-11e7-983e-6f92cf5bda1a.png" width=300/>

By default the privacy was "private":
<img src="https://user-images.githubusercontent.com/30171182/33230469-2c023aca-d1e4-11e7-997e-83cd36bd59eb.png" width=300/>

**Comment by Aldarone** [comment]
Ok, I missed something and I tested it again. I'll sum it up : 

With a protected account, the « follow request » menu item is visible in Mastalab, I can't change the default visibility in the Mastalab settings and it appears that the default visibility is forced to « private » (which is ok even if I would prefer to still be able to change the default visibility in the settings)

With an unprotected account, the « follow request » menu doesn't show up in Mastalab (ok), I can change the default visibility in Mastalab settings and set it to « private » (ok) but if I reply to a « public » toot, the visibility of the reply is set to « public » by default (not ok).

![convert](https://user-images.githubusercontent.com/2682011/33230594-b5e1a864-d1e6-11e7-8e9a-97b22150dd5c.png)


Are we on the same page ?

**Comment by stom79** [comment]
> the visibility of the reply is set to « public » by default (not ok).

Yes, it is what I need to improve because it is not applied for replies.

**Comment by stom79** [comment]
OK. It's fixed. Too bad, I published one hour ago the release 1.6.2 in prod which doesn't bring this bug fix. It will be for the next release.
