### ISSUE TITLE
Better Way to Display No. of Replies in Home Timeline

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [stom79/mastalab#6]
IMO, instead of showing the text 'replies' below the toot and the profile pic of all the users who replied, you could simply show the no. of toots beside the reply icon just like you do w/ boosts and favs. No need to show profile pics of users. That just clutters the home timeline.

**Comment by stom79** [comment]
Fully agree. Someone is working on that point. See: https://files.mastodon.social/media_attachments/files/001/746/241/original/7362ddd184a379a8.png
