### ISSUE TITLE
F-droid version not updated

### ISSUE THREAD

**Issue by ardydo** [stom79/mastalab#60]
Currently F-droid version still is 1.5.7 while version 1.6.2 has already been released. Just check [here](https://f-droid.org/packages/fr.gouv.etalab.mastodon/)
![image](https://user-images.githubusercontent.com/14042262/33236039-b40ea332-d22e-11e7-8ceb-7f70e2e25bf5.png)

**Comment by ardydo** [comment]
as a side note, I can't install any of the f-droid releases (from the releases on github) over my old instalation so maybe it has to do with signatures?

**Comment by stom79** [comment]
I wrote to Fdroid about this issue. Build fails with the message:
```
Failed to install the following SDK components:
  [Android SDK Platform 27]
  Please install the missing components using the SDK manager in Android Studio.
```
I updated the [metadata](https://gitlab.com/tom79/fdroiddata/commit/47d8c7018d8b838e0e58be8b38ff18bcbc1a5cb8) to the last version, I hope this issue will be fixed soon.

> as a side note, I can't install any of the f-droid releases (from the releases on github) over my old instalation so maybe it has to do with signatures?

Yes, signatures are not the same, so you need to uninstall the Fdroid release to get the new one.

**Comment by stom79** [comment]
It has been fixed by Fdroid today :)

**Comment by ardydo** [comment]
Today I just caved in and installed it from play store "I'll just switch
back when it's fixed"

Guess what? Hahaha

Thanks :)
