### ISSUE TITLE
Emojos are not displayed in the notification column 

### ISSUE THREAD

**Issue by Aldarone** [stom79/mastalab#63]
Toots in the notification column contain emojos shortcode instead of actual emojo.

**Comment by stom79** [comment]
It sounds to be related to this bug #46 which has been fixed. What version do you use?

**Comment by Aldarone** [comment]
1.6.3 I saw the upgrade this morning.

**Comment by stom79** [comment]
Could you PM me at @tom79@mastodon.social for a test?

**Comment by stom79** [comment]
Thanks it looks related to a refresh issue. I will fix that.

**Comment by stom79** [comment]
OK. It's fixed.
