### ISSUE TITLE
Error when boosting/faving from non-default account.

### ISSUE THREAD

**Issue by jfmcbrayer** [stom79/mastalab#64]
Sometimes, I get "Oops, an error occurred" when boosting or faving a toot from another account.

I've looked into this, and it appears that this failure happens when boosting/faving a toot that is appearing in the home timeline as boosted. If I click through to the original toot, I can then boost it from any of my accounts. So it seems like there may be a problem with looking up toots for boosting from secondary accounts if you are looking at the boost and not the original toot.

(Side note, thanks for all your hard work on Mastalab. Over the last month or so, it's gone from "looks good, but can't replace Subway Tooter because of features" to "daily driver".)

**Comment by stom79** [comment]
> So it seems like there may be a problem with looking up toots for boosting from secondary accounts if you are looking at the boost and not the original toot.

Thanks for this investigation, it will help a lot to fix this issue.

And thanks for your encouraging message and your help in this project!

**Comment by stom79** [comment]
I pushed [an APK](https://github.com/stom79/mastalab/blob/587c8ef749b168be1f21a433a0301551bfb2c413/app/safetynet/release/app-safetynet-release-1.6.3-fix-cross_actions.apk?raw=true) which should solve this issue.

**Comment by stom79** [comment]
Fixed in https://github.com/stom79/mastalab/releases/tag/1.6.4
