### ISSUE TITLE
Make notification bar dark in Night mode

### ISSUE THREAD

**Issue by elmindreda** [stom79/mastalab#65]
Currently the notification bar stays the same bright gray color when Night mode is enabled, which (subjectively, for me) is very distracting when the rest of the screen uses a dark background.

Thank you for a wonderful client!

**Comment by stom79** [comment]
Thanks, I will improve this part. 
I would like that some people interact on this thread to choose a [new color](https://material.io/guidelines/style/color.html#color-color-palette). Or one of the color scheme:

<img width="854" alt="capture d ecran 2017-11-28 a 06 58 17" src="https://user-images.githubusercontent.com/30171182/33304507-9231c0fa-d409-11e7-9035-3e90dbe7cf8d.png">

**Comment by stom79** [comment]
Thanks for this suggestion. I changed the color.

<img src="https://user-images.githubusercontent.com/30171182/33304991-3c6fb296-d40c-11e7-96d4-b7f8bbf846c0.png" width=300/>
