### ISSUE TITLE
No image apart from profile

### ISSUE THREAD

**Issue by clement-analogue** [stom79/mastalab#71]
There are no image displayed in mastalab apart from the one from my profile.

Version: beta 1.6.0
Instance: toot.forumanalogue.fr

**Comment by stom79** [comment]
I will also need your Android version. I created an account on this instance and I don't get any problems with images (profile pictures/media) from toots or boosts. Thanks.

**Comment by clement-analogue** [comment]
Android 4.1.2

**Comment by stom79** [comment]
Could you try this [Fdroid release](https://github.com/stom79/mastalab/blob/6210e6f0e3d21c6d8814fb3dc26fed91f80f21f3/app/fdroid/release/app-fdroid-release-1.6.3-test-1.apk?raw=true) that I built?

**Comment by clement-analogue** [comment]
I installed it. When I launched it, I have a message `Oops ! an error occured!`
![2017-12-01-18-49-41](https://user-images.githubusercontent.com/1931507/33496054-112f0540-d6c9-11e7-8404-f1d1c0454d25.jpg)

**Comment by stom79** [comment]
Do you use play services? If yes, could you test this [release](https://github.com/stom79/mastalab/blob/4da8f7fadeb9adc3d1f7de4eb9fee37e27b2a61b/app/safetynet/release/app-safetynet-release-test-1.apk?raw=true).

**Comment by clement-analogue** [comment]
Yes, I use Google Play Service. Unfortunately, I don't have choice on my phone.

I tried the new build. After cleaning the cache, the error message was gone, however, it doesn't solve the problem.
![2017-12-01-23-42-23](https://user-images.githubusercontent.com/1931507/33506974-6cfc2c3a-d6f2-11e7-867e-cfef30993ef2.jpg)
![2017-12-01-23-42-29](https://user-images.githubusercontent.com/1931507/33506982-750e3922-d6f2-11e7-976a-40c43adb2177.jpg)

**Comment by stom79** [comment]
Do you use a VPN?

**Comment by stom79** [comment]
I added another lib for pictures. I only applied changes for toots. Could you test [this apk](https://github.com/stom79/mastalab/blob/d8252ed9aae16530a2aa085147d63dc3314c4e4d/app/safetynet/release/app-safetynet-release-test-2.apk?raw=true) and tell me if it's better.  Thanks

**Comment by clement-analogue** [comment]
No VPN, but the instance is on my local network.
The last build is working! I had to remove all data, log in again and it worked! Thank you! :)

**Comment by stom79** [comment]
Great! So I removed the previous lib (and another one). I will publish the new release soon.

**Comment by stom79** [comment]
Fixed in https://github.com/stom79/mastalab/releases/tag/1.6.4
