### ISSUE TITLE
Share posts from the Android Tumblr app to Mastalab causes Mastalab to crash

### ISSUE THREAD

**Issue by stom79** [stom79/mastalab#73]
Cf. https://wandering.shop/@DialMforMara/99099946025953026

**Comment by PhotonQyv** [comment]
@stom79 I'm looking at this one, think I have a fix, just testing it now.

**Comment by PhotonQyv** [comment]
@stom79 I've PR'd the fix. It works, but might need a tweak as mentioned in PR (#74 ).

**Comment by stom79** [comment]
I think they might have some edge effects with sites that don't work with encryption. I will see how to fix that.

**Comment by PhotonQyv** [comment]
@stom79 It might indeed. A fix, but perhaps not the best fix (;*

**Comment by stom79** [comment]
Fixed in https://github.com/stom79/mastalab/releases/tag/1.6.4
