### ISSUE TITLE
Weird issue with mentions in 1.6.4.1

### ISSUE THREAD

**Issue by jfmcbrayer** [stom79/mastalab#77]
This is weird, and I'd be surprised if you can reproduce it, but in this version, clicking on a toot to get to the thread will, instead, take me to the profile page of the first person mentioned. Even when I'm sure I'm clicking on the opposite side of the toot from the mention.

Instance: glitch.social

Mastalab version: 1.6.4.1

Android version: LineageOS 14.1 (Android 7.1.2)

**Comment by stom79** [comment]
I moved a piece of code that manage this part, so I guess it comes from that.
I manage to reproduce a similar bug:

- Click on a mention in a toot => Opens the profile (OK)
- Go back to the timeline (back press)
- Click somewhere else in the same toot => Opens again the profile and not the related discussion thread.
- Go back to the timeline (back press)
- Click somewhere else in the toot => Opens again the discussion thread.

There is clearly a problem with clicks. I will investigate.

**Comment by stom79** [comment]
OK. It should be fixed. At least, I no longer get the bug that I described.

**Comment by jfmcbrayer** [comment]
I don't have a version installed with the fix, but I wanted to add another piece of information. It doesn't have to be a mention; if the first thing in the toot is a hashtag, taps on the toot away from the hashtag will also go to the hashtag search page.

**Comment by stom79** [comment]
My bad, I forgot to attach an apk for tests. Here it is: [Fdroid](https://github.com/stom79/mastalab/blob/1801c606b5511719caef726b5816247536ba829d/app/fdroid/release/app-fdroid-release-1.6.4.1-fix.apk?raw=true).

**Comment by jfmcbrayer** [comment]
Argh, I have it from play store, so I'd have to delete and reinstall to do F-Droid APK (sigs), right?

**Comment by stom79** [comment]
@jfmcbrayer You should not need to deinstall. When I build APKs (Google Play or Fdroid) I use the same key to sign it which is the one used for Google.
Deinstallation is only needed when switching to the apk built by Fdroid (FDroid uses its own key).

**Comment by jfmcbrayer** [comment]
It appears to be fixed, though I had to jump through some hoops to install it (I guess because LineageOS is weird?).

**Comment by stom79** [comment]
@jfmcbrayer Sorry, I missed your reply. I guess a key issue. Make sure the app is uninstalled for every users.
