### ISSUE TITLE
Can't save video 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#91]
There's a little save button when viewing a video (mp4) and I granted it storage access when asked the first time I pushed it, but it didn't work then and doesn't work on subsequent attempts. 

Toot from which I was trying to save: https://mastodon.social/users/yogthos/statuses/99131174545244330/activity

---

Instance: mstdn.io 

Mastalab version: 1.6.4.1

Android version: 7.1.2

**Comment by stom79** [comment]
Thanks for the report. It's fixed.
