### ISSUE TITLE
Clicking a url never works the first time 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#92]
What it says on the tin. Always takes 2-3 taps to open a url. 

Mastalab version: 1.6.4.1

Android version: 7.1.2

**Comment by stom79** [comment]
I think it's related to the bug #77 
Could you try the apk attached to this comment: https://github.com/stom79/mastalab/issues/77#issuecomment-349414453

**Comment by deutrino** [comment]
That does indeed appear to fix it! 😃

Will newer versions from the Play Store update over that apk properly?

**Comment by stom79** [comment]
Updates with Google should work because I used the same key :)
