### ISSUE TITLE
"bouncing" behavior when trying to scroll down on user profiles 

### ISSUE THREAD

**Issue by deutrino** [stom79/mastalab#98]
Steps to reproduce:

1. Load a user profile 
2. Attempt to scroll dkwn

What actually happens:

Scrolling "bounces" back to the top one or more times before working normally. 

What I expect to happen:

Scrolling should work normally. 

---

Instance: several 

Mastalab version: 1.6.4.1 via #77

Android version: 7.1.2

**Comment by stom79** [comment]
Are you using an apk that I put in an issue (not an official one)?

**Comment by deutrino** [comment]
I updated to 1.6.5.1 and there is still bouncing happening when trying to scroll down in user profiles. It doesn't happen every time or with every scroll, but it's not uncommon. I'll try to characterize it better.

**Comment by deutrino** [comment]
I'm still not sure what causes this to happen more or less often, but it's still very common for me.

**Comment by stom79** [comment]
Could you give working examples with some profiles?

**Comment by deutrino** [comment]
I have a hunch this has to do with the animation of the user profile pic.

**Comment by Fidgetcetera** [comment]
Just to pipe in, in my experience what happens here is that if your finger is released from the screen while scrolling in either direction, but the user's background image/icon section of the screen is still visible, it will "bounce" back up to the top of the profile page.
On the other hand, if your finger is released from the screen while at all past that point, it "bounces" down past the bio immediately and into a user's posts. 

When I'm not paying attention and just trying to scroll normally (which for me is flicking my finger on only a very small portion of the screen and letting the screen keep going) it bounces and prevents me from going to the posts of a user unless I intentionally scroll my finger farther. 

Is this about what you're experiencing, @deutrino?

**Comment by deutrino** [comment]
That's exactly it. I think it happens on every profile.

**Comment by stom79** [comment]
Initially, the scroll will hide the profile, thus only posts are visible with tabs. What can create this bounce, it is when clicking on the first tab (which allows to scroll to the top of the user's posts). Could you upload a small video capture?

**Comment by deutrino** [comment]
https://framadrop.org/r/MLAKzmrYcg#gzTguHnJlnyRTkLo8J1r84gzvr27U0/P+dwMdk7PiOk=

**Comment by stom79** [comment]
OK. Thanks. So, it's a normal behavior. If the screen is not enough scrolled down, it will go back to its original position.

**Comment by stom79** [comment]
It's fixed
